### ISSUE TITLE
Trigger Name Must be Unique

### ISSUE THREAD

**Issue by AlexAkulov** [moira-alert/moira#10]
Trigger Name must be unique. It is necessary for a better automatization.

**Comment by borovskyav** [comment]
For trigger uniquines we are using a triggerID, so it is quite enough for trigger identity. Now trigger name can be same in other projects, and user can find trigger they need by tag. It also applies to automatization to create new triggers. For example you can create new trigger while deploy new elastic cluster for team "Team1" with tag "Team1", and then create trigger with same name for team "Team2" with tag "Team2". So with this pattern you can unify all trigger in company between all teams
