### ISSUE TITLE
Allow windows line endings in protocol

### ISSUE THREAD

**Issue by genuss** [moira-alert/moira#104]
Hi! It looks like windows `\r\n` is not allowed as line delimiter in moira however for example `collectd` uses this delimiter since the very beginning (see https://github.com/collectd/collectd/blob/master/src/utils_format_graphite.c).
Could you please allow these two characters as separators?

**Comment by titusjaka** [comment]
Hi, 
Do you use Graphite-relay and which one? It seems to be relay's goal to trim line endings and resend to graphite storage and Moira in proper format.

**Comment by genuss** [comment]
No I don't  use relay, I just put metrics directly to moira. It was a test environment, I just picked up the docker-compose installation https://github.com/moira-alert/doc/blob/master/docker-compose.yml
Should I make the architecture like that?
````
                                  moira
metrics -> carbon-relay (some) ->                     
                                  carbon-cache (some) -> metrics database
````

**Comment by titusjaka** [comment]
Yep, that should work fine 😄

**Comment by genuss** [comment]
Allright, will try that.
