### ISSUE TITLE
Graceful shutdown of telebot listener

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#12]
If you use telegram bot, you make sure that you use telebot listener only on one instance of Moira. For this we are using distributed lock and extend it every half-ttl time interval. But if we can not extend it while lock record not foul, another instance can register bot and start new listener. In this case we should stop listener on addled instance. But telebot does not support graceful shutdown of pooling goroutine.
Now i use dirty hack and try to register bot again, after fail to extend of lock record. In most cases this solution can help. But such situation is possible.

**Comment by borovskyav** [comment]
Create pull request tucnak/telebot#99

**Comment by kamaev** [comment]
closed in https://github.com/moira-alert/moira/pull/67
