### ISSUE TITLE
Expected to see a webhooks in moira (use case inside)

### ISSUE THREAD

**Issue by vkochev** [moira-alert/moira#123]
We want a service (daemon) to track statistics from different sources (graphite is one of the sources).

In case the statistics indicate problems in our application, the daemon will help to display a message for users on the application page.

**Comment by kamaev** [comment]
Hi! It seems that web services shouldn't trigger transitions into a bad state this way.
This mechanisms should belong to services itself (have inner counters of processed items, /health status in api, etc..), not monitoring or alerting tools.
I'll keep this ussue open, but this feature won't solve the problem you described.

**Comment by vkochev** [comment]
The demon's purpose is only to warn the developer and help to display the message. The decision is made by the developer.

Health-status is one of the ways, of course.

**Comment by beevee** [comment]
Хочу в 2.5 такой MVP:

Добавляем новый тип контакта webhook. Этот тип контакта параметризуется единственной строкой: URL, куда отправлять запросы. На каждый эвент по этому URL делается POST-запрос с телом в формате JSON, содержащим информацию об эвенте. Содержимое JSON нужно обсудить исходя из того, какая информация есть в эвенте.

Дальнейшим развитием в следующих версиях может быть кастомизация тела запроса.

**Comment by borovskyav** [comment]
Документацию по этой задаче можно объединить с документацией на script-сендер (https://github.com/moira-alert/moira/issues/214), логика очень сильно похожа.

**Comment by borovskyav** [comment]
Договорились заменять в URL'e вот эти поля:
```
${contact_id} - Contact.Id
${contact_value} - Contact.Value
${contact_type} - Contact.Type
${trigger_id} - Trigger.Id
```

Зафиксировали контракт:
```
Events: 
    Event[]:
        Metric
        Value
        Timestamp
        IsTriggerEvent
        State
        OldState
Trigger:
    Id
    Name
    Description
    Targets
    WarnValue
    ErrorValue
    IsRemote
    Tags
Plot    
Contact:
    Id
    Value
    User
```

**Comment by sashasushko** [comment]
@borovskyav а что здесь по вебу?

**Comment by borovskyav** [comment]
Здесь нет веба :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by borovskyav** [comment]
@sashasushko наврал! На вебе нужно поддержать новый тип сендера, по аналогии с script сендером.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by borovskyav** [comment]
В вебе нужно добавить новый тип сендера по типу script с иконкой, договоритесь там с @kamaev какую иконку вставить.

**Comment by sashasushko** [comment]
↑ вынес задачу по фронту в отдельную ишью

**Comment by sashasushko** [comment]
@kamaev фронт и конфиг смёржены. Закрывай ишью, как будешь готов

**Comment by beevee** [comment]
https://github.com/moira-alert/doc/blob/b7aebc80431698845353e608bf393654d231c782/notifier.example.yml#L74-L91
