### ISSUE TITLE
Tags support

### ISSUE THREAD

**Issue by biancalana** [moira-alert/moira#142]
Does moira support tags for configure triggers ?
For tags I mean Graphite since 1.1.x series, supports storing data using tags to identify each series. (https://graphite.readthedocs.io/en/latest/tags.html)

**Comment by kamaev** [comment]
Hi, @biancalana!
Unfortunately not. But we're planning on adding this feature in the next 2-3 months.

**Comment by Pliner** [comment]
The first step of tags support will consist of the following:
1. `Filter` will not filter by tags, only by name.
2. `aliasByTags`,` groupByTags` will be supported (these functions are supported by `go-graphite`), but ` seriesByTag` seems unsupported by `go-graphite` now and it will be done in the next step.

**Comment by Pliner** [comment]
The next step of tags support:

`seriesByTag` is supported by go-graphite, but there are a lot of work to integrated it to Moira: querying of tags has to be supported to use it.

```
tag=spec    tag value exactly matches spec
tag!=spec   tag value does not exactly match spec
tag=~value  tag value matches the regular expression spec
tag!=~spec  tag value does not match the regular expression spec
```

**Comment by biancalana** [comment]
Great to see you pushing that forward!

I would like to help implementing tagdb with redis, I will post here later the functions signature so we can agree on that I before start

**Comment by Pliner** [comment]
Actually, we decided to implement it in other way: instead of querying suitable metrics in `checker` with TagDB, we are going to capture them in `filter` and fetch in `checker`(as it's done for simple metrics patterns).

You can follow the progress in #294 and we can discuss the decision there :wink:
