### ISSUE TITLE
Restore 'expression' key in API

### ISSUE THREAD

**Issue by sashasushko** [moira-alert/moira#15]
Now on `moira-test` there isn't "expression" key in response on request for trigger data. In `dev-` and `production-moira` this key exist. Where is truth?

**Comment by sashasushko** [comment]
Also is gone "is_simple_trigger" key

**Comment by borovskyav** [comment]
Field "is_simple_trigger" no more need in trigger structure. Now it is calculated on the fly. I did it in this commit https://github.com/moira-alert/moira/commit/5e10f567d2b6734b8f4e2dabf70a3d34429aebe0

**Comment by borovskyav** [comment]
Have fixed in https://github.com/moira-alert/moira/commit/419d3b0447e2ba7cb717ad0c80c5f3a85e39231b
