### ISSUE TITLE
redigo: getting dial tcp: connect: cannot assign requested address

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#163]
Отжирает все коннекции при большой нагрузке

**Comment by borovskyav** [comment]
Нарыли несколько проблем: 
1. Неограниченный пул соединений: решили потестировать, начнем со значения 512 с флагом ```wait``` в клиенте редиса.
2. Перерасход соединений из-за ленивого(через defer) их закрытия, а так же слишком активная аллокация (и возвращение) соединений вместо их переиспользования. хотим сделать несколько шагов:
   - где это нужно вызывать методы доступа в Database с уже полученным соединением, так чтобы один вызов методов Database соответствовал одному вызову ```connector.pool.Get()```;
   - заменить 3 вызова методов Database в [FetchData](https://github.com/moira-alert/moira/blob/develop/metric_source/local/fetchdata.go#L12), каждый из которых берет коннекцию из пула одним вызовом и брать только одну коннекцию;

**Comment by Pliner** [comment]
Как итог, сделали чуточку по-другому:

1. В #253 заиспользовали `SPOP N`, чтобы вынимать сразу пачку триггеров, вместо кучи одиночных `SPOP`. 
2. В #242 выставили минимальный и максимальный размер пула(раньше минимальный размер был 3, а максимальный - не ограничен), пофиксили возможность существования на стеке нескольких открытых соединений из-за закрытия через `defer`. Так же развели пулы соединений под блокировки и под обычные соединения(раньше был общий пул), так как не хотелось бы, чтобы блокировки конфликтовали с обычными запросами за соединения.
