### ISSUE TITLE
Fix rising/falling mode selector when switching between simple and advanced modes

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#172]
![2018-11-28_16-48-32](https://user-images.githubusercontent.com/7278994/50524568-4fe3b100-0af8-11e9-86da-20730661fa96.gif)

**Comment by sashasushko** [comment]
Вместе с багом фиксим неявное поведение, когда значения из _Simple mode_ использовались в _Expression_, как переменные.

Теперь при создании нового тригера или редактировании старого засылаем либо `warn_value` и `error_value`, либо `expression`. Если в `expression` они используются как переменные, кидаем ошибку валидации (на сервере и бэкенде).

Таким поведением исправим ошибку "источник правды", описанную в #235

**Comment by borovskyav** [comment]
На backend'e нужно будет впилить такую же валидацию.

**Comment by sashasushko** [comment]
@kamaev закрой ишью, как на бэке сделаешь, плез

**Comment by borovskyav** [comment]
Даша в параллельной задаче https://github.com/moira-alert/moira/issues/171  делала кусок кода и почти полностью сделал работу на бэке. Решили с ней объединить оба ишью.

**Comment by sashasushko** [comment]
@borovskyav а почему ишья в done на доске, но не закрыта?

**Comment by borovskyav** [comment]
Упс, косяк
