### ISSUE TITLE
Make moira-url configurable in web docker container

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#173]
ToDo:
- [x] придумать, где хранить подобный конфиг
- [x] реализовать такой конфиг
- [x] научить веб с ним работать

**Comment by sashasushko** [comment]
@beevee @kamaev нужны ваши мозги

**Comment by titusjaka** [comment]
Это не то, что нужно? https://webpack.js.org/api/cli/

**Comment by sashasushko** [comment]
Это тогда нужно package.json править или Makefile

> Это не то, что нужно? https://webpack.js.org/api/cli/

**Comment by borovskyav** [comment]
А это проблема? Мы же все равно пользователю уже готовую статику даем, все билды через make сами вызываем.

**Comment by sashasushko** [comment]
Давай сегодня на планировании обсудим. Моя твоя не понимать

**Comment by sashasushko** [comment]
Итак, проблема такая:

путь до АПИ передаётся в конструкторе АПИ в джаваскрипте. При выполнении в браузере. Поэтому его нельзя зачитать ниоткуда, кроме как из `window`.  Зачитать, например, из переменной окружения можно только при сборке.

**Comment by sashasushko** [comment]
Закинул в чат разработчиков, может, кто-то подскажет идею.

**Comment by borovskyav** [comment]
Сейчас как костыльный вариант обсуждаем дать пользователям возможность билдить веб с указанием ```node env {api_path}```

**Comment by sashasushko** [comment]
@borovskyav 
А как это попало в 2.5 и почему?

**Comment by borovskyav** [comment]
Ну мы такие сидели на планировании, а потом я такой: "о, давайте возьмем эту задачу!"

**Comment by sashasushko** [comment]
Давай тогда на 2.5 MVP - описать в доке, где менять адрес в JS и собрать себе контейнер, если хост тот же, и пару ссылок на проксирование в популярных сервер-системах, если хост другой.

@borovskyav что думаешь?

**Comment by borovskyav** [comment]
Слушай, я хотел это сегодня обсудить и забыл, мне кажется я придумал как её по нормальному делать. Давай на летучке обсудим

**Comment by sashasushko** [comment]
Тогда запиши себе на встречу 1 марта обсудить

**Comment by borovskyav** [comment]
договорились

**Comment by kamaev** [comment]
Closed in: https://github.com/moira-alert/web2.0/pull/258
