### ISSUE TITLE
Do not show tags that exist in local browser storage, but don't exist server-side

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#175]
При входе на главную страницу мойры мы пытаемся подставить в поисковую строку теги из хранилища браузера. Если в хранилище сохранен какой-нибудь тег, но его нет в мойре, то он всеравно подставится.

**Comment by sashasushko** [comment]
По итогам обсуждения:

- проверить насколько быстро будет отрабатывать код, который сравнит теги в `localstorage` со списком тегов на бэкенде
- по итогам замеров либо пофиксить, либо оставить как есть

**Comment by sashasushko** [comment]
А ещё меня бесит, что при сохранении в `localstorage` тега с главной, чтобы отфильтровать триггеры, он подставляется в форме создания тригера.

**Comment by beevee** [comment]
А ты можешь просто в фоне время от времени подтаскивать тэги с бэкенда и обновлять локалсторадж? Так, чтобы пользователь этого не заметил. Или я неправильно проблему понял?

**Comment by sashasushko** [comment]
> время от времени подтаскивать тэги с бэкенда и обновлять локалсторадж

Это не решит проблему, когда пользователь зашёл: теги у него несуществующие, а значит мы не можем подтянуть триггеры
