### ISSUE TITLE
Fix layout with long words (or URLs) in trigger description and name

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#176]
Сейчас в описание триггера можно вставить длинную ссылку (например), и она раздвинет страницу по горизонтали. Особенно в мобильной версии заметно. При длинном названии триггера едут иконки справа.

**Comment by sashasushko** [comment]
@borovskyav не могу воспроизвести 

> При длинном названии триггера едут иконки справа.

Дай больше контекста, пожалуйста
