### ISSUE TITLE
Fix publicly accessible icons for Slack sender

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#180]
ОКАЗЫВАЕТСЯ мы иконки для слака брали из веба мойры. Мы про это забыли когда переписывали этот самый веб. Хочется вернуть эти иконки назад и сделать так чтобы они были доступны без авторизации. Так же хочется добавить какую-нибудь документацию по поводу того как 
отдаются эти иконки.

Ссылка на старые иконки: https://github.com/moira-alert/web/tree/master/static/public

Должны отдаваться по адресу: moira.skbkontur.ru/public/fav72_error.png и moira.skbkontur.ru/public/fav72_ok.png

- [x] backend
- [x] doc

**Comment by sashasushko** [comment]
По итогам обсуждения:

- перенести иконки к нам
- совместно с @kamaev решить, как отдать наружу только папку public
- зафиксировать это в документации и докер-композ файле

**Comment by sashasushko** [comment]
Решено следующее:
- подготовить иконки для всех состояний триггеров
- отразить в документации, куда загрузить их в Слаке и как прописать в конфиге
- приложить в документации наши "нейтральные" иконки, на случай, если клёвые ребята, которые хотят использовать Мойру, не хотят заморачиваться с рисованием 

Потому что:
- нам не нужно думать, как сделать папку `public`
- клёвым ребятам, которые планируют использовать Мойру, не придётся думать о папке `public`
- мы не хардкодим свой УРЛ до иконок в конфигах, если вдруг ты это предлагал
- этот поход позволяет клёвым ребятам, которые используют Мойру, кастомизировать иконки
- кастомизация Слака производится средствами Слака

**Comment by beevee** [comment]
Если выпиливаем папку `public`, то надо не забыть, собственно, ее выпилить. Чтобы не оставалось легаси.

Но у меня есть вопрос. Мойра присылает зеленую иконку, когда алерт со статусом `OK`, и красную, когда алерт с другим каким-нибудь статусом. Через веб-админку Слака для бота можно загрузить только одну иконку. Разные иконки для разных сообщений достигаются путем передачи в API вместе с сообщением урла картинки. Если мы выпиливаем папку `public` и даем пользователям набор иконок, правильно ли я понимаю, что они должны будут найти какой-то хостинг и сами туда выложить картинки, чтобы получить полный экспириенс удовольствия от Мойры?

**Comment by sashasushko** [comment]
> Если выпиливаем папку public, то надо не забыть, собственно, ее выпилить. 

В 2.0 версии фронта папки уже нет. @kamaev проверь, пожалуйста, нет ли ничего для неё на бэке. Или делегируй знающим.

> Через веб-админку Слака для бота можно загрузить только одну иконку

Иконок можно загрузить столько, сколько надо. Погляди на наше пространство — https://kontur.slack.com/customize/emoji Подцепить к боту можно разные картинки по условию, @kamaev ответит лучше меня на этот вопрос.

>  они должны будут найти какой-то хостинг и сами туда выложить картинки
Только если не хотят добавлять их в свой Слак. В варианте со Слаком хостинг не нужен, стоит только добавить иконку в пространство.

**Comment by kamaev** [comment]
Да, сейчас план просто заюзать поле `IconEmoji` вместо `IconURL` и прокинуть в конфиг поле `use_emoji`. С Мойрой будем поставлять полный набор иконок и список алиасов, которые понадобятся слаку, чтобы распознать какую иконку запросил сендер. В доку добавим ссылку как добавить в слак кастомный emoji.

**Comment by kamaev** [comment]
Старые иконки были только в вебе: https://github.com/moira-alert/web/tree/master/static/public

**Comment by sashasushko** [comment]
ps. Ну и к нам в Слак можно втащить ;-)

**Comment by borovskyav** [comment]
- [x] backend
- [ ] doc

**Comment by borovskyav** [comment]
- [x] backend
- [ ] doc
