### ISSUE TITLE
Mark all dangerous Graphite functions as such (show a warning)

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#182]
Если в поле есть функция summarize (как пример, нужно составить список всех неугодных функций), подсвечивать желтым, показывать тултип с описанием, почему так. Надо составить список таких функций. Допилить документацию.

ToDo:
- [ ] Backend
- [ ] Frontend
- [ ] Doc

**Comment by borovskyav** [comment]
Самое интересное: 
Синхронизироваться с текущей версией локальной carbon-api и тем списком функций, которая там есть. Пакет metadata.go, наполняется всеми необходимыми функциями при старте приложения (проверить).
Синхронизироваться с функциями, которые есть в remote графите (если есть соединение), для этого есть метод ```GET /functions/```.

На основании списка для каждого сорца строить список "плохих" функций.

**Comment by borovskyav** [comment]
Рассмотреть возможность показа предупреждения при выставлении большого интервала для функций типа ```moving...```. Рекомендовать использовать remote графит, если такая опция доступна.

**Comment by borovskyav** [comment]
Попросил @beevee cобрать список «плохих» функций, на которые мы ходим ругаться. Желательно так чтобы это можно было превратить в адекватную документацию.

**Comment by sashasushko** [comment]
@borovskyav нужно проработать два момента:
- нужна схема выражения и критерии плохих функций, чтобы понять, как написать регулярку на ту строку, которую вводит пользователь.
- нужен дизайн, как и где у поля ввода показывать предупреждение.

**Comment by borovskyav** [comment]
Плохие функции будут прилетать с апи, для этого сделаем отдельный метод. По поводу дизайна, стоит ли сильно запариваться? Обычным тултипом справа с текстом не получится отъехать?

**Comment by sashasushko** [comment]
Как MVP визуально можно тултип или просто текст снизу. Но тексты "почему?" вдобавок к списку плохих функций нужны всё равно.

**Comment by borovskyav** [comment]
Для этого я привлек @beevee, который это все в доку оформит, будем на нее ссылку в тултипе давать.
Предлагаю MVP такой: понимаем что в тарегете есть "плохая" функция, подсвечиваем инпут желтым, показываем тултип. В нем имя "плохих" функций (их может быть несколько введено) и краткое описание, почему они"плохие". За подробностями отправляем в доку.

**Comment by beevee** [comment]
На странице создания/редактирования триггера, если пользователь сделал одно из:

- отредактировал target (с задержкой 1000ms);
- поменял выбор радиобаттона remote trigger.

...нужно отправить на бэкенд запрос `???validate` с содержимым:

```
{
  "target": "function(secondFunction(metric.name),100)",
  "remote": false
}
```

...где `target` — содержимое поля target, а `remote` имеет значение `false` только если выбран радиобаттон Redis.

В ответ сервер вернет содержимое:

```
{
  "syntax_ok": true,
  "bad_functions": {
    "moreFunction": "There is no such function in this version of Moira"
  }
}
```

...где `syntax_ok` имеет значение `false` в тех случаях, когда выражение совсем нельзя распарсить (например, не совпадают открывающие и закрывающие скобки). `bad_functions` содержит словарь, в котором ключами являются имена функций, использованных в таргете, а значениями — текст предупреждения, которое нужно показать пользователю про эту функцию.

Если функция хорошая, то ее не будет в `bad_functions`. Если плохих функций вообще нет, то ключа `bad_functions` не будет в ответе.

Флаг `syntax_ok` обозначает критичные проблемы в таргете. Если он имеет значение `false`, то такой триггер не сохранится. Словарь `bad_functions` содержит предупреждения для пользователей, но не мешает сохранению триггера.

Опционально можно подсвечивать в таргете цветом предупреждения подстроки `functionKey(`, где `functionKey` — ключи из словаря `bad_functions`.

**Comment by borovskyav** [comment]
https://github.com/go-graphite/carbonapi/blob/895336436a213bef2e5cf2769acb2d8f36337644/COMPATIBILITY.md

**Comment by beevee** [comment]
Critical errors (display error message, disallow saving):

* any invalid expressions (mismatching brackets, etc) that can't be evaluated
* functions that do not exist for the appropriate metric source (local/remote)
* any time intervals larger than `metrics_ttl` for the appropriate metric source (local/remote)

Warnings (display warning message, but allow saving):

functions | message
---------- | ---------
removeAbovePercentile, removeBelowPercentile, smartSummarize, summarize | This function is unstable: it can return different historical values with each evaluation. Moira will show unexpected values that you don't see on your graphs.
averageAbove, averageBelow, averageOutsidePercentile, currentAbove, currentBelow, filterSeries, highest, highestAverage, highestCurrent, highestMax, limit, lowest, lowestAverage, lowestCurrent, maximumAbove, maximumBelow, minimumAbove, minimumBelow, mostDeviant, removeBetweenPercentile, removeEmptySeries, useSeriesAbove | This function shows and hides entire metric series based on their values. Moira will send frequent false NODATA notifications.
alpha, areaBetween, color, consolidateBy, cumulative, dashed, drawAsInfinite, lineWidth, secondYAxis, setXFilesFactor, sortBy, sortByMaxima, sortByMinima, sortByName, sortByTotal, stacked, threshold, verticalLine | This function affects only visual graph representation. It is meaningless in Moira.
