### ISSUE TITLE
Support fulltext search API on web

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#185]
В версии 2.4 появилась возможность использовать полнотекстовый поиск по триггерам, теперь самое время втащить это на фронт

**upd 18.01.2019**

ToDo:
- [ ] переделать дизайн выдачи триггеров
- [x] добавить подсветку найденного вхождения
- [x] добавить кусок описания, если найденное вхождение в нём
- [x] удаляется поведение по Enter для выбора последнего или единственного найденного тега
- [x] по Enter теперь отрабатывает поиск

**Comment by sashasushko** [comment]
По итогам обсуждения:

- решить по дизайну
- обсудить с остальной командой

**Comment by borovskyav** [comment]
На бэке: в ответе на метод Search выводить размеченные поля Description или Name, для подсветки на фронте

**Comment by borovskyav** [comment]
Предлагаю в результате запроса search (в апи) добавить новое поле ```highlight``` с массивом элементов, по размеру равным массиву триггеров, и отсортированным в том же самом порядке.
Поля такие:
```
TriggerID:
Name:
Description:
```
Для каждого триггера из массива list предлагаю создавать такой элемент в массиве ```highlight``` с тем же самым индексом в массиве и заполнять те поля, в которых наш движок поиска нашел совпадения и подсветил. Например, если при запросе поиска апи нашел совпадения в Desription в триггере SomeId, то объект будет выглядеть так:
```
TriggerID: SomeID
Description: Что-то из этого будет подсвечено.
```

@kamaev предлагаю тебе разобраться с тем как bleve умеет подсвечивать совпадения и договориться с @sashasushko о контракте. Если есть какие-то предложения, замечания то давайте обсуждать!

**Comment by borovskyav** [comment]
Да, это мы уже поняли. Видимо будем возвращать подобный контракт прямо из индекса.

**Comment by borovskyav** [comment]
Один нюанс @sashasushko не забудь пожалуйста переехать на ```/search``` для поиска вместо ```/page```
