### ISSUE TITLE
Fix last two points on graphs when allowRealtimeAlerting is disabled

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#188]
В графиках видна дыра в конце. Метрика чекается на минуту позже, чем должна, если она не realtime

**Comment by A1bemuth** [comment]
So, I've been trying to reproduce this and it seems like the problem does not exist anymore. Here's an example of a notification for an event that happend at t-1h (non-realtime).
```
⭕️ERROR local.random.diceroll [dice] (2)

09:51: local.random.diceroll = 162 (NODATA to OK)
09:54: local.random.diceroll = 595 (OK to ERROR)
```
![image](https://user-images.githubusercontent.com/9745433/74928205-df35dd00-53fa-11ea-8342-87931393b2ca.png)
