### ISSUE TITLE
Tell user who turned on maintenance mode (and when)

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#192]
При выставлении maintenance совершенно не понятно, кто это сделал. Это может привести к вопросам, что делать с метрикой в тот момент, когда прошел maintenance интервал. Маинтейнить снова или уже все хорошо?

В первую очередь хочется знать, кто ставил maintenance на метрику.
Можно подумать о том, стоит ли вводить возможность написать комментарий к maintenance.

Стоит подумать: 
Как это показывать?
Как оформить комментирование?

**Comment by beevee** [comment]
![2019-01-09_18-30-10](https://user-images.githubusercontent.com/1009675/50902529-ebe8b300-143c-11e9-9c5e-bdb385367b68.png)

**Comment by borovskyav** [comment]
`— записывать в базу, кто и когда установил maintenance`

 Ты описал ситуации, когда maintenance закончился сам и мы прислали алерт, а не хотим говорить, что если maintenance был снят вручную, то кто его снял?

**Comment by beevee** [comment]
Да, можно писать.

Maintenance was set by user alexkir at <time> on <date> and removed by user kamaev at <time2> on <date2>.

**Comment by sashasushko** [comment]
А для чего это будет храниться? Только для последнего `maintenance`?

Я не могу понять UI, как показывать то, что триггер снят с обслуживания:
- до каких пор это показывать?
- что будет, если триггер дважды ставили и снимали с обслуживания

**Comment by borovskyav** [comment]
В результате запроса api/trigger/{TriggerID}/state добавится новое поле ```MaintenanceWho``` c таким контрактом:
```
{
  "start_user": "" - string
  "start_time": "" - timestamp
  "stop_user": ""
  "stop_time": ""
}
```

**Comment by sashasushko** [comment]
1. Что будет, если метрика не на обслуживании?
2. Что с триггерами на обслуживании?

**Comment by sashasushko** [comment]
> При снятом Maintenance на фронте ничего не показываем.

Зачем тогда
```
  "stop_user": ""
  "stop_time": ""
```

**Comment by borovskyav** [comment]
> Что будет, если метрика не на обслуживании?
Ничего, будут просто старые значения приходить.
> Что с триггерами на обслуживании?
Будет точно такое же поле в корне структуры
> Зачем тогда
Дофига делов сейчас выпиливать. Пусть будет.

**Comment by sashasushko** [comment]
> Поле тоже будет приходить со значениями, кто последний раз ставил в майнтенанс.

Это спорный момент. В 2.6 поспорим

> Дофига делов сейчас выпиливать. Пусть будет.

Хорошо, я тогда на это не завязываюсь

**Comment by borovskyav** [comment]
Кажется решение должно быть таким: если метрика (триггер) в мейнтенансе, и есть хотябы одно из полей ```maintenance_who.start_user``` или ```maintenance_who.start_time``` то нужно показать сообщение (иконку для тултипа, хз).

**Comment by borovskyav** [comment]
Саш, обрати внимание что start_user и start_time могут быть пустыми и это нормально. Как минимум потому что после релиза могут быть метрики в майнтенансе.

**Comment by sashasushko** [comment]
Тогда не будет всообщения?!

**Comment by sashasushko** [comment]
И ты мне скажи, ключи будут всегда, просто значения могут быть пустой строкой?

**Comment by borovskyav** [comment]
> Тогда не будет всообщения?!

Да

**Comment by borovskyav** [comment]
> И ты мне скажи, ключи будут всегда, просто значения могут быть пустой строкой?

Ключи будут всегда, но может быть и null

**Comment by sashasushko** [comment]
Веб смёржен

**Comment by sashasushko** [comment]
@borovskyav не забудь прееименовать:

```
{
  maintenance_info: {
    author_name: ?string,
    setup_time: ?number
  }
}
```

**Comment by sashasushko** [comment]
На фронте контракты поменял — moira-alert/web2.0/pull/248
