### ISSUE TITLE
Enhance NODATA protection

### ISSUE THREAD

**Issue by beevee** [moira-alert/moira#200]
## Как делать

Добавляем новый тип контакта — выключить Мойру. Это такой контакт, который переводит Мойру в состояние выключенных уведомлений, когда в него приходит любой негативный (!) эвент.

Этот контакт виден только администраторам Мойры. Только они могут создать подписку с этим контактом.

## Оригинальная формулировка

Рассматриваю это как MVP. Посмотрим, как будет работать. Если будет что улучшить — улучшим.

Защита от NODATA должна проверять условие каждую минуту и выключать уведомления, если это условие выполняется. Как и сейчас, уведомления выключаются автоматически, а включаются только вручную.

Пусть `x1, x2, ..., xn` — значения метрики «количество matched точек, прошедших через все фильтры в сумме за минуту». При этом `xn` — значение за последнюю _полную_ минуту.

`n=60` — длина истории метрики.

`с=0.7` — коэффициент падения нагрузки.

`t=5` — минимальная продолжительность аномалии (устанавливается равной половине TTL по умолчанию в минутах).

Собственно условие:
`∃N N≤n-t ∀k>N xk≤c*avg(x1, x2, ..., xN)`

По-русски: если начиная с какой-то точки N есть хотя бы t точек, каждая из которых меньше чем c умножить на среднее от всех предыдущих, то выключаем нотификации.

**Comment by beevee** [comment]
Конкретные значения для всех параметров взял из головы. Предполагаю, что значения этих параметров будут отличаться для разных инсталляций Мойры в зависимости от количества релеев, конфигурации сети и прочего. Отдельно нужно исследовать, какие значения будут хорошо работать для нас. Например, `c=0.7` я написал исходя из того, что у нас три релея. При равномерной нагрузке падение одного релея будет приводить к потере ~0.33 метрик, то есть приведет к срабатыванию условия.

**Comment by beevee** [comment]
А если нет NodataProtector-ов? Тогда отключается защита? А существующий способ защиты будем на новые рельсы переводить? Если не будем, получится два разных способа (плохо). Если будем, то хорошо бы, чтобы он по умолчанию у всех был, без создания чего-то вручную. Получается, нужно будет при установке Мойры какое-то количество дефолтных NodataProtector-ов заводить.

**Comment by kamaev** [comment]
> А если нет NodataProtector-ов?

Тогда будет только основной способ работать

> А существующий способ защиты будем на новые рельсы переводить?

Если при обсуждении п.2 прийдём к тому, что небольшой разницей во времени между:
- первым выставлением одному из меченых триггеров статуса `не-OK` **(чекер)** и 
- сменой значения `moira-selfstate:notifier-health` **(нотифаер)** 

можно пренебречь - то все можно будет оставить на старых рельсах 

> Получается, нужно будет при установке Мойры какое-то количество дефолтных NodataProtector-ов заводить.

Можно вхардкодить дефолтные переменные (в т.ч. таргет), для такого триггера (с учетом того что его создать можно будет только на hidden page) в веб

**Comment by kamaev** [comment]
*дефолтные значения переменных

**Comment by beevee** [comment]
Я придумал смешную идею.

Давайте не будем делать специальные триггеры типа NodataProtector. Давайте сделаем специальный тип _контакта_ — «выключить Мойру». Тогда мы можем подписывать выключатель Мойры на любой обычный триггер, или даже на несколько триггеров. Этот контакт может быть доступен только ограниченному кругу пользователей.

**Comment by titusjaka** [comment]
Чёрт, а это может сработать

**Comment by beevee** [comment]
MVPшная реализация норм работает, предлагаю больше ничего не делать тут.
