### ISSUE TITLE
Пустая картинка при переключении темы

### ISSUE THREAD

**Issue by ihard** [moira-alert/moira#205]
При переключении темы например со светлой на темную первое сообщение содержит пустую чёрную картинку. 
Уведомление в Telegram

**Comment by borovskyav** [comment]
Привет! Вы стабильно это ловили несколько раз? Мы знаем что есть кейсы, зависящие от триггера, когда прилетает пустая картинка и уже их пофиксили в #197.

**Comment by ihard** [comment]
Не получилось воспроизвести, закрываю.
