### ISSUE TITLE
Рендерить название триггера в сообщении в Телеграме ссылкой на сам триггер

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#211]
В последних версиях телеграма, можно делать любой текст ссылкой, предлагаю переделать наше сообщение в телеграме и рендерить название триггера ссылкой на сам триггер как это сделано у нас в слаке.

**Comment by ihard** [comment]
Ещё бы отдельное поле для произвольной ссылки и именем  (на график в графане или на описание на вики) и тоже вставлять как ссылку в сообщение.

**Comment by borovskyav** [comment]
@ihard я правильно понимаю что вы сейчас вставляете ссылку прямо в название триггера и по ней переходите? И слаком вы видомо не пользуетесь? Там такой сценарий работать не будет, потому что там имя триггера это и ссылка на него)
Если и правда вставляете, то для вас эта правка все сломает =(

**Comment by ihard** [comment]
Да, Slack не используем, Telegram +  почта. В именах сейчас почти все триггера такого вида:
`Нет платежей в магазин XX https://clck.ru/XXX`
и из сообщения сейчас можно перейти по ссылке, если прям вот просто включить в сообщении имя тригерра = ссылка, то все поломается :(
как workaround поэтому и просил или поле отдельное для ссылки или вы обсуждали вроде как markdown для description.

**Comment by borovskyav** [comment]
Понял, значит правка не имеет смысла, таких сценариев я не ожидал, этот issue закрываю.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
