### ISSUE TITLE
Better ticks for Y-axis on notification graphs

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#217]
Current notification graphs can show ugly autogenerated values for Y-axis ticks: **195.06, 210.06, 225.06, 240.06, 254.06, 269.06, 284.06, 298.06**. We need more user-friendly algorithm, something like this: http://vis.stanford.edu/files/2010-TickLabels-InfoVis.pdf

**Comment by beevee** [comment]
https://github.com/wcharczuk/go-chart/pull/120

Судя по другим пулл-реквестам в этом репозитории, ждать мержа можно долго. Поэтому собираюсь переключить временно Мойру на мой форк.
