### ISSUE TITLE
Refactor controls in add/edit subscription modal window

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#221]
Cancel button in subscription modal window confuses our users. They think it means "Cancel subscription", but it only closes modal window. We should remove this button.

Another problem is that Delete button is not accented enough. User can accidentally click on it and subscription will be deleted without any warning or question. This action cannot be undone. We should make this button red. 

See [this component from UI library](http://tech.skbkontur.ru/react-ui/#/Components/Button)

Look at screen
![screenshot_2019-03-01 moira - settings](https://user-images.githubusercontent.com/4469056/53620779-00b01e80-3c16-11e9-92a1-5ad0b4d4defb.png)

**Comment by aswinmprabhu** [comment]
Made a PR
https://github.com/moira-alert/web2.0/pull/224
