### ISSUE TITLE
Add username column to notification page

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#223]
Sometimes Moira administators have troubles with notification delivery when users set incorrect contact value (see https://github.com/moira-alert/moira/issues/222). Administrator needs to find who created this contact and ask this user to fix it.

We use hidden `/notifications` page to solve this task (see [docs on hidden pages](https://moira.readthedocs.io/en/latest/user_guide/hidden_pages.html)). But this page lacks information on user name.

So we decided show user name at notification page. In separate column. Look at screen
![screenshot_2019-03-01 moira - notifications](https://user-images.githubusercontent.com/4469056/53621723-46221b00-3c19-11e9-82a9-36e58ea4b1cd.png)

**Comment by sashasushko** [comment]
Что значит "владелец контакта"? Сейчас есть колонка _Contact_, а что должно быть?

**Comment by borovskyav** [comment]
В запросе ```https://moira.skbkontur.ru/api/notification?start=0&end=-1```, в котором возвращается массив нотификаций в очереди есть поле ```contact```, сейчас оттуда используется только поле ```value```. Предлагаю еще выводить поле ```user``` (имя владельца контакта) в отдельную колонку.

**Comment by lazycipher** [comment]
Hey @borovskyav,
Can I work on this?

**Comment by sashasushko** [comment]
Close by https://github.com/moira-alert/web2.0/pull/230
