### ISSUE TITLE
В типе уведомления script передавать ${trigger_name} как один аргумент

### ISSUE THREAD

**Issue by ihard** [moira-alert/moira#227]
Сейчас при таких настройках в notifier:
`    - type: script
      name: Jira
      exec: /etc/moira/scripts/jira-create-issue.py ${trigger_name} ${contact_value}
или
`    - type: script
      name: Jira
      exec: /etc/moira/scripts/jira-create-issue.py "${trigger_name}" "${contact_value}"`

если в имени триггера есть пробелы - имя разбивается на несколько аргументов для скрипта, что крайне неудобно использовать.

**Comment by borovskyav** [comment]
Как вариант мы можем делать на trigger_name URLEncode

**Comment by ihard** [comment]
А просто взять в кавычки имя триггера и контакта не получится? 
Даже если в строке exec я принудительно их добавляю, в аргументы прилетает разбитая строка по нескольким аргументам.

**Comment by borovskyav** [comment]
И это помогает?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ihard** [comment]
Не помогает ) что выглядит совсем нелогично.

**Comment by borovskyav** [comment]
Блин, я, честно говоря, вообще не понимаю какой смысл было давать это поле и не давать trigger_id. Сейчас большое желание задерпрекейтить trigger_name на самом деле. На крайняк по trigger_id можно и ссылку построить и запрос в мойру сделать.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ihard** [comment]
про trigger_id согласен, в любом случае как правило требуется доп информация о триггере и получить её проще по id

**Comment by borovskyav** [comment]
Да, самое то главное что вся инфа по триггеру летит в stdout, Тимур в чате мойры про это где-то месяц назад писал.

**Comment by borovskyav** [comment]
Ладно, кажется самое логичное кажется задепрекейтить trigger_name и выпилить его в 2.6. А сейчас протащить все те же поля, которые будет подменяться в url'e в #123

**Comment by borovskyav** [comment]
#123 закрыт
