### ISSUE TITLE
Add to script sender $trigger_id variable

### ISSUE THREAD

**Issue by ihard** [moira-alert/moira#228]
Для использования типа уведомления скрипт было бы удобно получать в качестве аргумента также trigger_id (по аналогии с $trigger_name), его можно сразу использовать или чтобы забрать дополнительную информацию (description например) о триггере по api.

**Comment by borovskyav** [comment]
Сейчас делаем задачу https://github.com/moira-alert/moira/issues/123. После это сделаем чтобы в path пробрасывались те же самые поля.

**Comment by borovskyav** [comment]
Закроем вместе с https://github.com/moira-alert/moira/issues/123

**Comment by borovskyav** [comment]
#123 Закрыт
