### ISSUE TITLE
Разрешить anonymous удалять или редактировать ранее созданные подписки

### ISSUE THREAD

**Issue by ihard** [moira-alert/moira#231]
Изначально мы включили у себя режим работы с индивидуальными пользователями, поработав некоторое время поняли что для работы в командах это совсем неудобно и переключили в режим одного пользователя. 
Как результат остались индивидуальные подписки которые можно увидеть на странице tags, но которые нельзя удалить или заменить. Пользователи которые их создали тоже уже их не видят, но они есть в базе и по ним работает notifier.

**Comment by borovskyav** [comment]
Такая потребность тоже у нас есть в первую очередь для удаления подписок уже уволившихся сотрудников и кривых подписок. Не думал что у кого-то еще возникает подобный кейс. В общем мы обдумаем это вопрос на летучке в понедельник. Хотя мне уже год говорят что пора разрешать изменять чужие подписки и контакты :)

**Comment by ihard** [comment]
В идеале, наверное, это добавить в конфиге api например, список пользователей (admins) у которых будет эта возможность изменять чужие подписки и контакты.

**Comment by Tetrergeru** [comment]
Сделали админам возможность редактировать чужие подписки и контакты

https://github.com/moira-alert/moira/pull/1024
