### ISSUE TITLE
Ошибка сохранения триггера при создании в "Advanced mode"

### ISSUE THREAD

**Issue by ihard** [moira-alert/moira#235]
Moira - 2.4.0.0-1
Cоздаем новый триггер через web интерфейс, заполняем t1 и выражение например "ERROR if T1 ≥" 5, затем переключаемся в "Advanced mode" и пишем выражение "t1 >= 10 : ERROR".
Переключаемся на Simple mode и сохраняем триггер - результат в web интерфейсе сохранился результат ввода из "Advanced mode" -  "Expression t1 >= 10 : ERROR."

**Comment by sashasushko** [comment]
Спасибо!

Объединяем с #172
