### ISSUE TITLE
Add special tag (?) to select all triggers for a subscription

### ISSUE THREAD

**Issue by ihard** [moira-alert/moira#236]
Задача которую хотелось бы решить - подписка которая будет ловить все сработавшие триггеры и отправлять их в отдельный канал уведомлений.
Было бы удобно иметь служебный триггер "any" или "*"  по которому можно было бы создать такую подписку (как workaround да можно конечно создать подписку и просто добавлять в ней все теги руками или скриптом, но выглядеть в интерфейсе это будет очень громоздко).

**Comment by borovskyav** [comment]
Эх, а мы только избавились от служебных тегов и тут нам прилетает 2 реквеста за неделю про добавление служебных триггеров =) Хорошо, мы подумаем в следующем релизе как решить эту проблему.
