### ISSUE TITLE
Hidden pages и apache

### ISSUE THREAD

**Issue by avinchakov** [moira-alert/moira#245]
Всем привет, а сейчас еще работают hidden pages?
У меня конфиг apache2:

```
<VirtualHost *:8443>
        ServerName moira.local
        DocumentRoot "/var/www/moira"
        LogLevel warn
        ErrorLog ${APACHE_LOG_DIR}/moira-web_error.log
        CustomLog ${APACHE_LOG_DIR}/moira-web_access.log combined
        SSLEngine on
        ...
        <Location />
                Include auth-ldap.inc.conf
                Require valid-user
                AddDefaultCharset UTF-8
                DirectoryIndex     index.html
                Options            -Indexes
                Order              Allow,Deny
                Allow              from all
        </Location>
        <Location /api>
                ProxyPass http://localhost:8081/api
        </Location>
</VirtualHost>
```
И ни одна скрытая страница не найдена.

**Comment by borovskyav** [comment]
Привет! Логика отображения скрытых страниц никак не отличается от логики отображения других страниц и никаких проблем от настроек балансировщика возникнуть не должно было.

**Comment by avinchakov** [comment]
Оно работало, раньше, но после какого-то из обновлений перестало)

**Comment by borovskyav** [comment]
Обновлений мойры? Если есть возможность, скажи версию мойры с какой и на какую обновлялся. И еще было бы интересно посмотреть в F12 вкладку Network при загрузке одной из скрытых страниц.

**Comment by borovskyav** [comment]
Ну или логи API

**Comment by avinchakov** [comment]
Сейчас версия 2.4. Точно е скажу когда перестало работать, но мне кажется с 2.3 или 2.2.
apache access-log:
`[08/Feb/2019:10:37:22 +0300] "GET /tags HTTP/1.1" 404 5240 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"`
В логах api пусто в это время

**Comment by sashasushko** [comment]
@avinchakov, а обычные страницы открываются по прямому УРЛу? Например, по `moira.local/settings`

**Comment by sashasushko** [comment]
Веб-морда — это SPA, и ей нужно, чтобы Апач (или любой другой сервер) на любой запрос к `moira.local` кроме `/api` отдавал `index.html`

**Comment by avinchakov** [comment]
Нашли причину, конфиг apache2 нужно было допилить...
```
<Directory /var/www/moira/>
                RewriteEngine On
                RewriteBase "/"
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteRule ^(.+) /var/www/moira/index.html
                DirectoryIndex     index.html
                Options            -Indexes
                Order              Allow,Deny
                Allow              from all
        </Directory>

        <Location />
                Include auth-ldap.inc.conf
                Require valid-user
                AddDefaultCharset UTF-8
        </Location>
```
