### ISSUE TITLE
Limit message size in Pushover sender

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#250]
Pushover API has a limit on length of various fields in message. We need to implement these restrictions in our Pushover sender.

API docs: https://pushover.net/api#messages
Library constants: https://github.com/gregdel/pushover/blob/master/pushover.go#L46
Pushover sender: https://github.com/moira-alert/moira/blob/master/senders/pushover/pushover.go

We need to update gregdel/pushover library (see fix below) and then:
1. Restrict Title length.
2. Restrict message length (probably already done).
3. Restrict URL length.

**Comment by borovskyav** [comment]
Законтрибютил в либу https://github.com/gregdel/pushover/pull/5

**Comment by aswinmprabhu** [comment]
I would like to work on this issue. Can you please tell me how exactly do propose to implement a restriction? What should be done if the message goes over the limit? Truncate it ?

**Comment by beevee** [comment]
@aswinmprabhu you can take this issue. You can refer to Telegram sender for implementation idea: https://github.com/moira-alert/moira/blob/8fb128733d66a2b2a4121c5cf147202dd9fecead/senders/telegram/send.go#L42-L44

**Comment by aswinmprabhu** [comment]
Ok. I used the telegram reference to limit the title. The message is already limited. I am not sure as to how to limit the URL size. Modifying the URL by shortening it is not an option as that will cause the URL to not work anymore.

**Comment by beevee** [comment]
If URL doesn't fit, we should just omit the URL entirely.
