### ISSUE TITLE
Limit message size in Slack sender

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#255]
Slack has a limit on message size, it's 40000 symbols (see https://api.slack.com/changelog/2018-04-truncating-really-long-messages). Our Slack sender currently ignores this limit, which leads to truncated and malformed messages. We need to implement this limit in our Slack sender in a similar fashion to Telegram message size limit (see https://github.com/moira-alert/moira/blob/8fb128733d66a2b2a4121c5cf147202dd9fecead/senders/telegram/init.go#L15).

Slack sender is here: https://github.com/moira-alert/moira/blob/master/senders/slack/slack.go

**Comment by aswinmprabhu** [comment]
Is this issue taken? If not I would like to make a PR for it.
