### ISSUE TITLE
Add a script named "dev" that runs fake api and starts the application in moira frontend

### ISSUE THREAD

**Issue by siddhant1** [moira-alert/moira#273]

**Comment by sashasushko** [comment]
We haven't `prod` script :-) So I don't think it's necessary.

But I understand, what you want. What you think, if we change `start` script that it started fake API? Like `start-local-api`

**Comment by sashasushko** [comment]
So, this how I see:

Rewrite `start`, `start-local-api` and `fakeapi` scripts in [package.json](https://github.com/moira-alert/web2.0/blob/develop/package.json) to 2 new.

First must start webpack-dev-sever and json-server in parallele.

Second must start only webpack-dev-sever and pass env variable `API_MODE=local` for webpack proxy option.

**Comment by siddhant1** [comment]
Working on it !

**Comment by siddhant1** [comment]
Should I do something like dev script which concurrently runs fakeApi and start script?

**Comment by sashasushko** [comment]
Yep

**Comment by hv7214** [comment]
Since there is no one assigned on this issue, i'm picking this.
