### ISSUE TITLE
Add eslint , prettier and flow checks before committing using husky

### ISSUE THREAD

**Issue by siddhant1** [moira-alert/moira#275]
I think we should add in an eslint check ,prettier formatter and flow checks before committing code.
Should I send in a pull request?

**Comment by sashasushko** [comment]
I don't like check with `--fix` option. Because I think developer must know, what and why changed in his code.

But if prehook only will notice about lint erros, it's good idea. It will clean commit history from "Fix eslint errors" commits :-)

**Comment by sashasushko** [comment]
So, this how I see:

- [ ] add precommit hook which run `yarn lint` and disable push until errors not fixed
- [ ] add script for flow check in package.json and precommit hook like for lint

**Comment by siddhant1** [comment]
Working !

**Comment by sashasushko** [comment]
@siddhant1 how are you going? Need help?

**Comment by siddhant1** [comment]
Sorry for late response , I will send a pr today

**Comment by sashasushko** [comment]
I asked, because other GSOC applicants want your tasks. If you will done it, okay.

**Comment by siddhant1** [comment]
Yeah if anyone is willing they can pick up

**Comment by hv7214** [comment]
i see this is a small task. I am picking this. @sashasushko there are lot of flow errors, so for now should i leave flow-check ?

**Comment by sashasushko** [comment]
@hv7214  It's okay. Just ignore them. We have task for GSOC to rewrite Flow to TS. We also will fix those errors
