### ISSUE TITLE
Prometheus alert manager

### ISSUE THREAD

**Issue by gmlexx** [moira-alert/moira#281]
I would like to propose integration between the strongest parts of prometheus and Moira in the form that Moira could act as Prometheus alert manager
https://prometheus.io/docs/alerting/alertmanager/
In other words would be great if Moira could understand Prometheus alerts (as Moira events) and display them in UI.

**Comment by borovskyav** [comment]
Привет! Я уже мельком пытался разбираться. Вот такие мысли приходят в голову:
- Использовать мойру просто как красивый фронт для создания алертов в проме. У этого есть одна большая проблема: вся конфигурация подписок и триггеров идет через файлы конфигурации. Кажется не наш вариант
- Использовать мойру со всей той функциональностью которая есть сейчас. Все, что нужно сделать это использовать другой [metric_source](https://github.com/moira-alert/moira/blob/develop/metric_source/source.go). Этот вариант куда проще для реализации. Мне здесь видятся 2 проблемы, которые на самом деле не сильно влияют на MVP: Слишком захламленная страница триггера. Её в любом случае нужно переделывать, но сейчас вариант с тем что от Sourc'a у нас будет меняться сам способ заполения таргета надо доделывать в любом случае. Вторая проблема: это несколько инсталяций прометеуса, каждая со своими данными, что является довольно частым паттерном при больших объемах метрик.

**Comment by gmlexx** [comment]
Привет,
Может можно начать с малого, например ограничиться только настройкой уведомлений и визуализацией уже пришедших алертов. Пусть они по-прежнему настраиваются где настраиваются, функция менеджера алертов в прометеусе только в их обработке.

**Comment by borovskyav** [comment]
@gmlexx Я на самом деле совсем не имею опыта с промом, и не до конца уверен про схему прома с тем как у него создаются подписки и триггеры. Мне казалось что там любая сущность даже уведомления настраиваются через файл.

**Comment by gmlexx** [comment]
@borovskyav да, в проме все настраивается через файлы, что вот прямо супер неудобно, когда это касается простых вещей вроде настройки куда присылать уведомление, потому что обычные пользователи этого сделать никогда не смогут. Поэтому и хочется эту часть взять из Мойры. В проме это не связанные между собой настройки, например так описываются "триггеры"

>       rules:
>         - alert: RunOutOfDisk
>           annotations:
>             description: "{{ $value }}% on {{ $labels.host }} {{ $labels.path }}"
>             summary: Low disk space
>           expr: disk_used_percent > 90
>           for: 10m
>           labels:
>             severity: warning
>             environment: prod

А так описываются куда отсылать уведомления:

>       #Prod alerts channel
>       - name: "prod-slack"
>         slack_configs:
>           - send_resolved: true
>             api_url: https://hooks.slack.com/services/...
>             channel: "#prod-alerts"
>             color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
>             title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Prometheus Event Notification'
>             title_link: '{{ template "slack.default.titlelink" . }}'
>             pretext: "{{ .CommonAnnotations.summary }}"
>             text: |-
>               {{ range .Alerts }}
>                 {{- if .Annotations.summary }}*Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`{{- end }}
>                 *Description:* {{ .Annotations.description }}{{ .Annotations.message }}
>                 *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:>{{ if or .Annotations.runbook .Annotations.runbook_url }} *Runbook:* <{{ .Annotations.runbook }}{{ .Annotations.runbook_url }}|:spiral_note_pad:>{{ end }}
>                 *Details:*
>                 {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
>                 {{ end }}
>               {{ end }}
>             fallback: '{{ template "slack.default.fallback" . }}'
>             icon_emoji: '{{ template "slack.default.iconemoji" . }}'
>             icon_url: '{{ template "slack.default.iconurl" . }}'

Плюс настройки роутинга - по сути матчинг на тэги

>         - match_re:
>             job: (.*prod.*)
>           receiver: "prod-slack"  
> 

Т.е. по сути я не предлагаю трогать первую часть, пусть она так и будет.
В каком-то роде это тот же триггер, только вместо tag-ов там labels.
Пока хочется заменить только убогий UI для отображения пришедших алертов.

**Comment by beevee** [comment]
Сделаем в #366.
