### ISSUE TITLE
Edit controls in modal windows on notifications page

### ISSUE THREAD

**Issue by sashasushko** [moira-alert/moira#284]
After [previous issue](https://github.com/moira-alert/moira/issues/221) we decided edit all controls like that.

So, need remove "Cancel" button in `CreateSubscriptionModal.jsx`, `NewContactModal.jsx` and `ContactEditModal.jsx`. In `ContactEditModal.jsx` also make Delete button red.

**Comment by aswinmprabhu** [comment]
This one's simple enough. I'll take it

**Comment by sashasushko** [comment]
Okay

**Comment by sashasushko** [comment]
Sorry, I clicked wrong button
