### ISSUE TITLE
Add markdown support for trigger description

### ISSUE THREAD

**Issue by sashasushko** [moira-alert/moira#285]
Now in description we can parse only `\n` breaks. Thanks for
```css
word-break: break-word;
white-space: pre-wrap;
```

We want add markdown support for description textarea in trigger add/edit pages:
![screenshot_2019-03-05 moira - add trigger](https://user-images.githubusercontent.com/4469056/53786355-53067d80-3f3d-11e9-8491-ba4d31622ab9.png)
![screenshot_2019-03-05 moira - trigger - 12321](https://user-images.githubusercontent.com/4469056/53786363-5863c800-3f3d-11e9-9686-72b77fd6ba45.png)

We already use [Remarkable](https://www.npmjs.com/package/remarkable) for markdown in `ContactEditForm.jsx`. You can use this package or to argument why we need replace it for another.

## Double kill
It's be cool, if you create preview for description, like in Github or similar.
![screenshot_2019-03-05 moira - edit trigger](https://user-images.githubusercontent.com/4469056/53786372-61ed3000-3f3d-11e9-8d23-1e913ce4e2c5.png)

## Fatality
In `ContactEditForm.jsx` we get markdown string from server. We trust it. In this case description writes by users. It's be cool, if you protect us from XSS.

**Comment by aswinmprabhu** [comment]
I would like to work on this

**Comment by sashasushko** [comment]
Okay, but first, pls, close #284
