### ISSUE TITLE
Add sorting to Patterns page

### ISSUE THREAD

**Issue by sashasushko** [moira-alert/moira#287]
We have hidden page with all patterns in Moira. Look at `/patterns`.

Need add sorting up/down by columns *Triggers* and *Metrics*:
![screenshot_2019-03-05 moira - patterns](https://user-images.githubusercontent.com/4469056/53790164-1ab86c80-3f48-11e9-92bb-d96d1aa38e39.png)

For example can be take soring in *Current state* table on trigger page:
![screenshot_2019-03-05 moira - trigger - staging moira redis cpu utilization per core](https://user-images.githubusercontent.com/4469056/53790301-771b8c00-3f48-11e9-82b7-d7c26784d2ca.png)

# Attention
Need collaborate with assigned person for issue #286

**Comment by lazycipher** [comment]
I would like to work on this.

**Comment by sashasushko** [comment]
Okay

**Comment by lazycipher** [comment]
Hi @sashasushko,
I tried accessing `/patterns` hidden page but I get nothing in there. It's blank.
I followed [README.md](https://github.com/moira-alert/web2.0/blob/master/README.md) of web2.0. to set it up locally.

[See Screenshot](https://imgur.com/qIEXSDW)

**Comment by sashasushko** [comment]
Yep, I forgot duplicate ToDo to this issue. Look at https://github.com/moira-alert/moira/issues/286

> add patterns fake data to fake api based on json-server. To simplify development

**Comment by sashasushko** [comment]
@lazycipher maybe split this issue and #286? There is few guys who want to help with this issue

**Comment by lazycipher** [comment]
@sashasushko I've already started working on this issue after generating fakeapi data for #286.
We can split the `adding data` and `defer rendering`. But I'm willing to work on these.
I had a busy week in college and now I've 4 days holiday.

**Comment by sashasushko** [comment]
Okay :-)

**Comment by hv7214** [comment]
@sashasushko `/patterns` page is showing `undefined` error. I've also started fakeapi server at 9002.
![Screenshot from 2020-02-16 16-04-10](https://user-images.githubusercontent.com/42354803/74603137-5d7e4080-50d6-11ea-9e9c-a5c6f5000d4a.png)

**Comment by sashasushko** [comment]
@hv7214 you need add some patterns fake data to fake api based on json-server

**Comment by hv7214** [comment]
@sashasushko i guess that data is supposed to be in db.json, right ?

**Comment by sashasushko** [comment]
@hv7214 yep. Unfortunately now it is supported manually

**Comment by hv7214** [comment]
Should i open an issue for same ?

**Comment by sashasushko** [comment]
Not necessary. Thanks. There are only two issues for trigger page. This and #286

**Comment by hv7214** [comment]
i'm taking this up

**Comment by sashasushko** [comment]
@hv7214 look at https://github.com/moira-alert/web2.0/pull/291

**Comment by hv7214** [comment]
@sashasushko thanks for reducing the effort. I was going to write fake patterns data :smile:

**Comment by sashasushko** [comment]
Fixed in https://github.com/moira-alert/web2.0/pull/292
