### ISSUE TITLE
Do not autodisable notifications for fresh Moira installations

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#288]
Moira has built-in NODATA protection that disables all notifications when Moira itself breaks. For example, if there are no incoming metrics, there is no need to send NODATA notifications to all subscribers: it's obvious that Moira itself is broken. In this case, only Moira administrators get notifications.

See: https://github.com/moira-alert/moira/blob/develop/notifier/selfstate/selfstate.go

This protection mechanism backfires on new Moira installations that naturally lack any incoming metrics.

1. When there are no incoming metrics, selfcheck mechanism will detect a condition that "there are no incoming metrics for a long time". Perhaps, we should disable this condition when there are no metrics in the database at all.
2. When there are no triggers, selfcheck mechanism will detect a condition that "there were no trigger checks for a long time". Perhaps, we should disable this condition when there are no triggers in the database at all.

Also, we should make log message more clear. Instead of:

```
WARNING	Stop sending notifications for 10s: notifier in a bad state: ERROR
```

...we should log:
```
WARNING	Stop sending notifications for 10s: notifier in a bad state: ERROR. Fix SelfState errors and turn on notifier in /notifications page 
```

**Comment by ZeyadYasser** [comment]
I would like to work on this issue, Thank you!

**Comment by beevee** [comment]
Sure, OK

**Comment by borovskyav** [comment]
Will be done in #364
