### ISSUE TITLE
Replace auth type in smtp

### ISSUE THREAD

**Issue by proffust** [moira-alert/moira#292]
Now auth plain is used, which is very insecure, you must either change it to AUTH LOGIN, or go through authentication methods when receiving the response "504 5.7.4 Unrecognized authentication type" from the mail server

**Comment by mikaelmello** [comment]
`net/smtp` does not support LOGIN, only PLAIN and CRAM-MD5.

However, I did found this:

https://gist.github.com/homme/22b457eb054a07e7b2fb

Can I submit a PR?

**Comment by mikaelmello** [comment]
After reading a bit more about the topic, it seems to me that LOGIN does not provide any more security than PLAIN.

They seem to ask for the same credentials (username + password) and are both sent in plain text. In fact, I found people saying that PLAIN is better [[1]](https://dovecot.org/list/dovecot/2011-November/079233.html). That would probably explain why `net/smtp` does not even have it as an authentication method.

Also, the security is guaranteed by encryption in the _transport level_ [(more details here)](https://security.stackexchange.com/a/146527/127403). Which the sender does provide by enabling TLS.

That said, I don't see why you would need the LOGIN auth when PLAIN is implemented. Does your SMTP server only allow LOGIN? If so, that is unexpected.

**Comment by mikaelmello** [comment]
Is it reasonable to close this issue?

**Comment by borovskyav** [comment]
@proffust waiting for your answer =)

**Comment by proffust** [comment]
Ok, I close issue
