### ISSUE TITLE
Types of Triggers

### ISSUE THREAD

**Issue by AlexAkulov** [moira-alert/moira#3]
We could add different types of triggers
- Push Type for real time alerting. It is like current trigger type.
- Pull Type for simple detect anomalies. This trigger has to pull data from graphite storage periodically, like all other monitoring systems based on graphite. (bosun, beacon)
- HeathCheck Type is a standard shedulled check HTTP, FTP and some other popular protocols like (statuscake.com, uptimerobot.com)
- WatchDog is a trigger that waits for periodical http requests that sets its state. It is necessary for tracking the state of sparse and periodical operations like backups (healthchecks.io, deadmanssnitch.com)

**Comment by beevee** [comment]
Push and pull types are already implemented. Other types we are not going to implement.
