### ISSUE TITLE
Fix maintenance selector by DRY principles in Moira Mobile Web UI

### ISSUE THREAD

**Issue by sashasushko** [moira-alert/moira#305]
We have mobile version for Moira Web UI. Unfortunately, it was developed in a hurry, so its code is not "clean" in some places. It needs some refactoring.

There is modal windows for choice maintenance time in files `MobileMetricsListItem.jsx` and `MobileTriggerInfo.jsx`. Code that describes this modals doesn't follow the DRY principles.

**ToDo**
- not break compatibility
- look up at data in `Domain/Maintenance.js`
- based on this data replace spaghetti code to clean and simple cycle

**Warn!**
To check you solution, you need to run Moira locally. Then in developer tools of your browser enable the adaptive mode and open the Moira Web UI. Then:
![trigger-maintenance-1](https://user-images.githubusercontent.com/4469056/54519587-b1454e80-4988-11e9-88b4-e2ae86fc369a.png)
![trigger-maintenance-2](https://user-images.githubusercontent.com/4469056/54519593-b3a7a880-4988-11e9-9cdc-d27376753851.png)

----
Please, [look at two our major rules for contributors](https://github.com/moira-alert/web2.0#contributing)

**Comment by aswinmprabhu** [comment]
I can work on this.

**Comment by sashasushko** [comment]
@aswinmprabhu please give chance to others :-)
