### ISSUE TITLE
Update Storybook to 5.X.X version

### ISSUE THREAD

**Issue by sashasushko** [moira-alert/moira#308]
We use [Storybook](https://github.com/storybooks/storybook) in development. It's useful tool to organize showcase of components. Few weeks ago it upgrade to 5.X.X version. There are a lot breaking changes.

ToDo:
- read Storybook changelog and migration info
- update Storybook in Moira web to latest stable version
- fix all migration errors, if they will

----
Please, [look at two our major rules for contributors](https://github.com/moira-alert/web2.0/tree/develop#contributing).

**Comment by adrijshikhar** [comment]
@sashasushko i would like to work on this. can you please assign this issue to me?
PS- i have already setup the repo.

**Comment by sashasushko** [comment]
@adrijshikhar feel free to send pull request :-)

**Comment by alishamohanty** [comment]
Is this issue still available? I would love to work on it.

**Comment by sashasushko** [comment]
Let's ask @adrijshikhar

**Comment by alishamohanty** [comment]
Since @adrijshikhar haven't replied, can I take the task @sashasushko ?

**Comment by adrijshikhar** [comment]
Go ahead

**Comment by alishamohanty** [comment]
Thanks @adrijshikhar :D Working on this issue.

**Comment by sorovlad** [comment]
Updated into https://github.com/moira-alert/web2.0/pull/311
