### ISSUE TITLE
Update React Router to 5.X.X version

### ISSUE THREAD

**Issue by sashasushko** [moira-alert/moira#309]
Few days ago React Router and React Router DOM was upgrade to 5.X.X version.

**ToDo:**
- wait till React Router team write changelog for 5.X.X version
- update React Router in Moira web to latest stable version
- fix all migration errors, if they will

----
Please, [look at two our major rules for contributors](https://github.com/moira-alert/web2.0/tree/develop#contributing).

**Comment by sashasushko** [comment]
Some info about v5 - https://reacttraining.com/blog/react-router-v5/

**Comment by hv7214** [comment]
i am picking this up

**Comment by ani4aniket** [comment]
I guess @hv7214  is not working on this anymore. May I take this up @sashasushko.

**Comment by sashasushko** [comment]
It would be correct to wait for @hv7214 response, but @ani4aniket you are right, this is open source, so everyone can just send a pull request with a solution.

**Comment by hv7214** [comment]
@sashasushko it's okay, @ani4aniket go ahead

**Comment by ani4aniket** [comment]
Thanks, @hv7214 for maintaining the dignity of open-source.

**Comment by SrividyaKK** [comment]
@sashasushko  I saw that both react-router and react-router-dom packages have been installed. The react-router package is not needed, as react-router-dom would accomplish the tasks, wouldn't it?
