### ISSUE TITLE
Fix CSS chunks name

### ISSUE THREAD

**Issue by sashasushko** [moira-alert/moira#311]
In release 2.5 (now in `delevop` branch) of Moira Web we improved chunk split in Webpack. Now we have 4 bundles:
- `vendors` - all npm libraries
- `common` - common code between mobile and desktop vesions
- `desktop` - code for desktop version
- `mobile` - code for mobile version

Look at js files:
![image](https://user-images.githubusercontent.com/4469056/54610158-39ede880-4a76-11e9-942f-2ec8a94845fe.png)

Implicit advantage was that styles also was splitted to chunks.

But there is problem with naming:
![image](https://user-images.githubusercontent.com/4469056/54610339-a23cca00-4a76-11e9-8c54-733c8ddb2c40.png)

Need to figure out why bundle name contains `id + entry_pount` not `chunk name` and fix it.

----
Please, [look at two our major rules for contributors](https://github.com/moira-alert/web2.0/tree/develop#contributing).

**Comment by Vivekrajput20** [comment]
I'm working on it.

**Comment by sashasushko** [comment]
Yep

**Comment by beevee** [comment]
Done in 2.5
