### ISSUE TITLE
Change font in plots to support more Unicode characters, like emojis

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#333]
People love emojis. We love emojis.

Can we use emojis in trigger names? Sure we can.

What do we get when we use our beloved 💩poop💩emoji💩 in graphs? That's what:
![dark expression](https://user-images.githubusercontent.com/1009675/61440449-fd1afb00-a95c-11e9-9ae3-46131b8deaa7.png)

A rectangle! That's no good. Perhaps, our default font is not very rich in popular Unicode characters.

Our plan is to find a new font, that:
1. Is distributed under an appropriate free license. Like Google Noto.
2. Contains at least tolerable version of our beloved poop emoji (along with all the latin characters and cyrillic characters, of course).
3. Belongs to a display-oriented, sans-serif family.
4. Isn't very large in file size and isn't encumbered with various bold, semibold, italic and thin varieties. We just need a regular one.

**Comment by kamaev** [comment]
Convert font.ttf to bytes (font.go) by using https://github.com/wcharczuk/file2bytes

**Comment by Nixolay** [comment]
feature/suport_unicode_characters_like_emojis
