### ISSUE TITLE
Disallow deleting tags that are used in existing subscriptions

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#344]
Сейчас это приводит к интересному спецэффекту:
Польвователь выбирает тег из тегов в подписках, но его нет уже в мойре. Сразу после выбора тег удаляется из поисковой строки.

**Comment by beevee** [comment]
А чо в ревью-то перевели? Где PR?

**Comment by Nixolay** [comment]
feature/subscriptions_tags
