### ISSUE TITLE
"Something unexpected happend to Moira" message

### ISSUE THREAD

**Issue by usbulat** [moira-alert/moira#351]
Hi!

Moira version 2.4.0

We faced some problem with message:
![error message](https://user-images.githubusercontent.com/22560358/56125998-cced4600-5f82-11e9-9499-93b10851a138.png)
It appears sometimes. We fix it with deleting redis db, and pulling triggers back with script. But after some time it appears again. And notifier stops sending messages, it sends only Moira Notifier health check messages that it is in ERROR state.
We also think that this can be caused by our one trigger which uses asPercentage and is in exception state (because we couldn't manage to make this function work properly. Is it working, because there was bug in previous version as I remember?).

Do you have any thougths or any suggestion about this issue? Is it a known bug?

**Comment by borovskyav** [comment]
Hi! This service message shows if self state monitor is turned off notifier if one part of Moira was in a bad state. See more info [here](https://moira.readthedocs.io/en/latest/user_guide/selfstate.html)

**Comment by usbulat** [comment]
Thanks, @borovskyav . I'll check this doc, but we haven't seen any errors in log files of moira services. Also we have all moira services in one docker container with only redis db volumed, and restart of container doesn't help, so I think that problem is in db data. I'll check more detailed next time when we'll face it again.

**Comment by borovskyav** [comment]
Main point: moira turns ERROR state automatically, but it can’t be automatic OK. So, usually steps looks like:
1. Moira checks services state, see that one of this does not works well, send self state alert, turns state ERROR (disable notifications)
2 You see this alert, and fix problems
3 Turn on notifications on notifications page.

**Comment by borovskyav** [comment]
You also can turn off notifications manually if moira in maintenance (for example, you are upgrading moira or reload relays)

**Comment by borovskyav** [comment]
> so I think that problem is in db data

No, your data can not affects moira state :) only working of moira parts (filter, checker, notifier, relay)
