### ISSUE TITLE
Markdown descriptions in senders

### ISSUE THREAD

**Issue by beevee** [moira-alert/moira#353]
Web UI supports Markdown descriptions since 2.5 (see #285), but Slack and other senders do not. We need to send descriptions as Markdown in all sender types that support it. And also maybe we need to convert Markdown for senders that support HTML or other types of markup languages.

**Comment by aswinmprabhu** [comment]
Hey. I can help. Slack supports basic MD I guess.
https://api.slack.com/docs/message-formatting#message_formatting

**Comment by aswinmprabhu** [comment]
Senders like pushover and slack seem to support basic HTML but not all of it. For example, the web UI supports MD headers which are converted to `h1` tags but these are not supported by pushover and slack.
https://pushover.net/api#html
What do we do in such cases?

**Comment by beevee** [comment]
We should:

1. Make sure all existing senders use Markdown properly, or at least strip formatting if they don't. For example, we can use full Markdown in Slack, we can convert to full unrestricted HTML for email, and to subset of HTML for Pushover, etc.
2. Make sure all existing senders use description to some extent, depending on message size limit. For example, Slack can use full description, Telegram can use first N characters of description, etc. SMS sender should probably use 0 characters of description :-)

For example, we can build a message for Slack (4000 characters limit) this way:
1. Render title, tags and all other short fields. Let's say this takes 100 characters, and we have 3900 left.
2. Render description, limited to some amount of characters that is less than total amount left. Let's say 3000. So even if we have a long description, we still have some characters left (900 in this case).
3. Render metric events with all characters left. If we don't have enough characters left, we can use "and N more events", like we do now.

**Comment by aswinmprabhu** [comment]
Slack's MD seems to a bit different.
The normal MD syntax supported by the web UI uses 2 * around the text for bold but slack uses just one * around the text.
Another point is that telegram and slack don't support MD headers that start with #. What should be done in these cases?

**Comment by beevee** [comment]
Try to convert to appropriate syntax where possible, and strip all unsupported syntax, leaving just plain text.

**Comment by beevee** [comment]
Message and description size fixed for Slack. Markdown formatting added to Slack. Description added for Email. #403

**Comment by beevee** [comment]
Other senders, like Telegram and Pushover, are not ready yet.
