### ISSUE TITLE
moira-checker - NaN 

### ISSUE THREAD

**Issue by avinchakov** [moira-alert/moira#357]
Добрый день, 
Пару лет назад я уже задавал вопрос, решение я так и не нашел.
Проблема так и осталась.
Имею:
```
# moira-checker -version
Moira Checker
Version: 2.5.0.0
Git Commit: 4c03982d9e87e38354a5b648971cda6f580811f3
Go Version: go1.11.5
```
Стоит carbon-c-relay. На машинах - collectd. С графитом (стоковый с whisper) проблем нет.
Вот пример триггера памяти с 4х серверов:
```
# moira-checker -t 0a750a6f-653e-4506-a006-86ad21469571
2019-04-18 11:28:30.530	checker	DEBUG	Checking trigger 0a750a6f-653e-4506-a006-86ad21469571
2019-04-18 11:28:30.533	checker	DEBUG	[TriggerID:0a750a6f-653e-4506-a006-86ad21469571] Checking metricData vault-dev-prod-02_local: [NaN NaN NaN NaN NaN NaN NaN NaN NaN]
2019-04-18 11:28:30.533	checker	DEBUG	[TriggerID:0a750a6f-653e-4506-a006-86ad21469571][TimeSeries:vault-dev-prod-02_local] Checking interval: 1555575496 - 1555576110 (60s), step: 614
2019-04-18 11:28:30.534	checker	DEBUG	[TriggerID:0a750a6f-653e-4506-a006-86ad21469571][TimeSeries:vault-dev-prod-02_local] Checkpoint: 1555575875
2019-04-18 11:28:30.534	checker	DEBUG	[TriggerID:0a750a6f-653e-4506-a006-86ad21469571] Checking metricData vault-dev-prod-01_local: [NaN NaN NaN NaN NaN NaN NaN NaN NaN]
2019-04-18 11:28:30.534	checker	DEBUG	[TriggerID:0a750a6f-653e-4506-a006-86ad21469571][TimeSeries:vault-dev-prod-01_local] Checking interval: 1555575496 - 1555576110 (60s), step: 614
2019-04-18 11:28:30.534	checker	DEBUG	[TriggerID:0a750a6f-653e-4506-a006-86ad21469571][TimeSeries:vault-dev-prod-01_local] Checkpoint: 1555575875
2019-04-18 11:28:30.534	checker	DEBUG	[TriggerID:0a750a6f-653e-4506-a006-86ad21469571] Checking metricData vault-cc-prod-02_local: [NaN NaN NaN NaN NaN NaN NaN NaN NaN]
2019-04-18 11:28:30.534	checker	DEBUG	[TriggerID:0a750a6f-653e-4506-a006-86ad21469571][TimeSeries:vault-cc-prod-02_local] Checking interval: 1555575496 - 1555576110 (60s), step: 614
2019-04-18 11:28:30.534	checker	DEBUG	[TriggerID:0a750a6f-653e-4506-a006-86ad21469571][TimeSeries:vault-cc-prod-02_local] Checkpoint: 1555575875
2019-04-18 11:28:30.535	checker	DEBUG	[TriggerID:0a750a6f-653e-4506-a006-86ad21469571] Checking metricData vault-cc-prod-01_local: [NaN NaN NaN NaN NaN NaN NaN NaN NaN]
2019-04-18 11:28:30.535	checker	DEBUG	[TriggerID:0a750a6f-653e-4506-a006-86ad21469571][TimeSeries:vault-cc-prod-01_local] Checking interval: 1555575496 - 1555576110 (60s), step: 614
2019-04-18 11:28:30.535	checker	DEBUG	[TriggerID:0a750a6f-653e-4506-a006-86ad21469571][TimeSeries:vault-cc-prod-01_local] Checkpoint: 1555575875
```
И такого у меня много. 
Предыдущий тикет https://github.com/moira-alert/worker/issues/44

Есть какое-то решение данной проблемы?

**Comment by kamaev** [comment]
Привет! 
Moira переписанная на Go обрабатывает данные несколько иначе, чем более ранние Python версии, что сейчас представляет из себя проблема?
Полученный output говорит о том, что по метрикам триггера не приходят значения

**Comment by borovskyav** [comment]
Привет, да, @kamaev все верно сказал. По логам кажется что проблемы нет, потому что по данным метрикам просто не приходят точки. Давай лучше поймем, правда ли этих точек не должно быть или это нормальное поведение и по метрикам просто перестали идти данные?

**Comment by borovskyav** [comment]
Как я понял раньше у тебя `Invalid Nan value when encoding double` проблема возникала, сейчас что-то подобное есть?

**Comment by avinchakov** [comment]
В том то и дело что данные постоянно пропадают в мойре, и срабатывает алерт. А по графиту - данные есть. 
Сам тригер прост:
Target
```
aliasByNode(asPercent(systems.vault-*-prod-0*_local.memory.memory.free, sumSeries(systems.vault-*-prod-0*_local.memory.memory.free, systems.vault-*-prod-0*_local.memory.memory.used)),1)
Value
Warning: 20. Error: 10. Set NODATA if has no value for 600 seconds
```

**Comment by borovskyav** [comment]
У нас есть два служебных метода в api, можешь посмотреть есть ли данные в метриках здесь:
´https://{moiraUrl}/api/trigger/{triggerId}/render´ - отобразит метрики графиком
´https://{moiraUrl}/api/trigger/{triggerId}/metrics´ - отобразит в виде json’a

**Comment by kamaev** [comment]
Нужно убедиться в том, что и у Графита и у Мойры в конфиге storage-schemas.conf указан одинаковый и соответствующий интервалу отправки ретешен для этих метрик. Также стоит проверить что сейчас показывают собственные метрики carbon-c-relay по очередям на отправку данных. Возможна ситуация при которой метрика не пришла вовремя, при это алертинг уже сработал, а в графит она только записалась

**Comment by avinchakov** [comment]
Схема одинаковая.
График очередей почти совпадает. Сильных отклонений нет.
По служебным методам взял более наглядный пример, в котором постоянно пустые метрики у разных инстансов:
Тригер:
`aliasByNode(derivative(vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.*.quickstats.overallCpuUsage),5)`

Render:
`{"status":"Internal Server Error","error":"no points found to render trigger: d71703ec-9073-49a3-9877-165d430ce0da"}`

Metrics:
`{"main":{"us-bl-esxi01":[],"us-bl-esxi02":[],"us-bl-esxi03":[],"us-bl-esxi04":[],"us-bl-esxi05":[],"us-bl-esxi06":[],"us-bl-esxi07":[],"us-bl-esxi08":[],"us-bl-esxi09":[],"us-bl-esxi10":[],"us-bl-esxi11":[],"us-bl-esxi12":[],"us-bl-esxi13":[],"us-bl-esxi14":[],"us-bl-esxi15":[],"us-bl-esxi16":[]}}`

При вызове moira-checker -t вижу такие записи:
`2019-04-19 06:46:15.467	checker	DEBUG	[TriggerID:d71703ec-9073-49a3-9877-165d430ce0da] Checking metricData us-bl-esxi14: [NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN]`

**Comment by borovskyav** [comment]
И по этому таргету в графите все строится, да?

**Comment by avinchakov** [comment]
Да, все без пробелов, данные идут.

**Comment by kamaev** [comment]
А через tcpdump метрики на машине с moira-filter отлавливаются?
Есть ли у него в логах какие то ошибки?

**Comment by avinchakov** [comment]
```
# tcpdump -An -i lo dst port 2005 | grep "quickstats\.overallCpuUsage" | grep esxi
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
E.../,@.@..9................].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi03.quickstats.overallCpuUsage 3619 1555659548
E.../9@.@..,................].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi02.quickstats.overallCpuUsage 2821 1555659548
E.../F@.@...................].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi09.quickstats.overallCpuUsage 2986 1555659548
E.../.@.@.................&y].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi10.quickstats.overallCpuUsage 966 1555659548
E.../.@.@.................+.].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi11.quickstats.overallCpuUsage 4637 1555659549
E.../.@.@.................5.].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi12.quickstats.overallCpuUsage 2223 1555659549
E.../.@.@..}..............:.].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi13.quickstats.overallCpuUsage 2343 1555659549
E.../.@.@..p..............?.].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi14.quickstats.overallCpuUsage 3315 1555659549
E...0.@.@..c..............D.].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi16.quickstats.overallCpuUsage 3508 1555659549
E...0.@.@..V..............J.].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi01.quickstats.overallCpuUsage 2255 1555659549
E...0.@.@..I..............O/].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi04.quickstats.overallCpuUsage 1875 1555659549
E...0)@.@..=..............TM].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi15.quickstats.overallCpuUsage 698 1555659549
E...06@.@..0..............Yj].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi05.quickstats.overallCpuUsage 668 1555659549
E...0C@.@.."..............^.].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi06.quickstats.overallCpuUsage 1407 1555659549
E...0P@.@.................c.].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi07.quickstats.overallCpuUsage 5008 1555659549
E...0]@.@.................h.].].P..V....vmw.us-vcsa_local.us-datacenter.us-vmcluster.esx.us-bl-esxi08.quickstats.overallCpuUsage 4257 1555659549
```

В логах ошибок нет. Уточню - у меня все на одном сервере. Проблем с памятью и CPU не наблюдаю.

**Comment by kamaev** [comment]
Если не трудно, скинь еще пожалуйста значения вот этих метрик, которые Мойра генерит сама:

```
{{ graphite }}.{{ prefix }}.filter.recevied.matching.count | nonNegativeDerivative() | scaleToSeconds(1)
{{ graphite }}.{{ prefix }}.filter.linesToMatch.95-percentile
{{ graphite }}.{{ prefix }}.filter.metricsToSave.95-percentile
```

и какой в конфиге фильтра установлен `cache_capacity`?

**Comment by avinchakov** [comment]
Метрики не были выключены, включил. Такого параметра вообще нет у меня в конфиге, поставил 10

**Comment by avinchakov** [comment]
Мне кажется я нашел проблему. Я в какой-то момент оставил дефолтные параметры в checker.yml.
Пока поставил так, и вроде работает:
```
checker:
  nodata_check_interval: 120s
  check_interval: 60s
  metrics_ttl: 1h
  stop_checking_interval: 180s
```
У меня все метрики пушатся раз в 60сек.

**Comment by borovskyav** [comment]
Странно что это помогло =)

**Comment by avinchakov** [comment]
ну плюс я рестартанул все) и поставил cache_capacity 10.
да, они.

**Comment by borovskyav** [comment]
cache_capacity=10 - это дефолтное значение оно бы и само проставилось.
Почему мы про это спрашивали - у мойры есть некоторая зависимость от количества входящих метрик и метрик для сохранения от cache_capacity.
Когда число входящих метрик и метрик для сохранения становится больше какого-то порога стоит поиграться с cache_capacity.
Мы это описывали в документации к конфигам:
> Number of metrics to cache before checking them.
Note: As this value increases, Redis CPU usage decreases.
Normally, this value must be an order of magnitude less than graphite.prefix.filter.recevied.matching.count | nonNegativeDerivative() | scaleToSeconds(1)
For example: with 100 matching metrics, set cache_capacity to 10. With 1000 matching metrics, increase cache_capacity up to 100.

**Comment by avinchakov** [comment]
![Снимок экрана 2019-04-23 в 10 17 28](https://user-images.githubusercontent.com/13016561/56556281-050f0d00-65b1-11e9-966f-6ed4f7489396.png)

**Comment by avinchakov** [comment]
вот еще метрики которые вы просили

**Comment by borovskyav** [comment]
Да, по графикам всё четко, давай подождем пару дней. Если воспроизведется снова - пиши. Потом мы закроем issue. Если вдруг опять будет повторяться открой ишью снова.

**Comment by avinchakov** [comment]
Хорошо, понаблюдаю - отпишусь. Спасибо большое.

**Comment by borovskyav** [comment]
Привет! Закрываю ишью, если будут проблемы пиши, продолжим разбираться)
