### ISSUE TITLE
Datasource Prometheus

### ISSUE THREAD

**Issue by beevee** [moira-alert/moira#366]
Втаскиваем Prometheus как датасорс по аналогии с remote Graphite.

1. Втащить датасорс: на уровне чекера понимать этот тип триггера, реализовать интерфейс MetricSource (взять из графаны).
2. Научиться в вебе переключать на этот датасорс и сохранять новый тип триггера в базе. По возможности втащить подсветку синтаксиса из какого-нибудь готового реакт-компонента (или из графаны!).
3. Валидировать триггер при сохранении.
4. Self check.

**Comment by flyik** [comment]
Добрый день. Скажите, пожалуйста, есть какие-нибудь прогнозы по времени?

**Comment by Pliner** [comment]
Думаю, что прогноз от пары недель до месяца, однако, речь про мердж в мастер. Вероятно, релиз будем собирать еще сколько-то времени.

**Comment by strangeman** [comment]
Ребят, добрый день, а есть прогнозы по данной фиче? Насколько я вижу, работы ведутся в ветке https://github.com/moira-alert/moira/commits/feature/prometheus-366, может ее уже можно пощупать, параллельно помочь с документацией, например?

**Comment by logicall** [comment]
Подскажите, пожалуйста, есть подвижки по Prometheus?

**Comment by paragor** [comment]
Можно ли расчитывать на релиз этой фичи в ближайшие месяцы? :)

Очень хочется интеграции с influxDb или Prometheus в качестве датасорса.

**Comment by f0y** [comment]
Мы в ЮMoney переезжаем с graphite на prometheus. Нам очень нужна данная функциональность. Хочется понять какие планы на реализацию этой фичи.

**Comment by Tetrergeru** [comment]
Сейчас снова взялись за реализацию интеграции с прометеусом.

О прогрессе буду иногда писать тут, на всякий случай

**Comment by Tetrergeru** [comment]
В мойру добавлена интуграция с прометеусом!

#848
