### ISSUE TITLE
Trigger schedule displayed without timezone

### ISSUE THREAD

**Issue by beevee** [moira-alert/moira#375]
I can create a trigger with a schedule using any timezone (or even without any timezone). Let's say I've created a trigger via API with a schedule active from 09:00 till 23:00 every day. And, of course, I forgot to set up my timezone offset (I'm at UTC+5).

In web UI I'll see something like this:
![image](https://user-images.githubusercontent.com/1009675/58940860-0f1d5180-8794-11e9-9cff-2457cd40f2c0.png)

You see, there is no mention that this schedule is defined for UTC+0 timezone, so I can expect it to be active from 09:00 till 23:00 in my timezone. But instead it will be active from 14:00 till 04:00.

There are two possible solutions:
1. Convert schedule to browser timezone.
2. Show actual timezone in which schedule was defined.

I personally prefer the first.

**Comment by hv7214** [comment]
@beevee @sashasushko if no one is working, can i pick this up ?

**Comment by sashasushko** [comment]
@hv7214 I tnink it's already taken — https://github.com/moira-alert/moira/issues/472

@beevee it's true?

**Comment by beevee** [comment]
Yes, we already have a PR for this issue. Just a small bug left.

**Comment by beevee** [comment]
Duplicated by #472
