### ISSUE TITLE
Support for additional delivery channels

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#377]
Moira supports a number of delivery channels such as email, Slack, Telegram, etc. to inform users that a certain trigger was activated (see Setting Up Your Subscriptions).

The aim of this project is to provide support for a number of additional delivery channels. To do so, one should talk to community and research possible channels to be added, contribute corresponding senders, and tune the web UI to allow users to create subscriptions using new channels.

**Comment by beliys** [comment]
Can I still request support for sending notifications through Rocket.Chat (https://rocket.chat/)?

**Comment by beevee** [comment]
This issue was worked on by @aswinmprabhu during Google Summer of Code 2019. Some delivery channels were added. Not Rocket.Chat, sadly.

If you are interested in new delivery channels, feel free to open a new issue (one issue per one delivery channel, please).
