### ISSUE TITLE
Add Prometheus endpoint for internal metrics

### ISSUE THREAD

**Issue by beevee** [moira-alert/moira#380]
Moira can send internal metrics to Graphite (and, of course, to itself). But we are moving towards Prometheus-only installations, so we need to be able to function without Graphite.

Internal Moira metrics should be available as a Prometheus-compatible endpoint.

**Comment by biancalana** [comment]
Moira is going to discontinue graphite metrics support ?

**Comment by borovskyav** [comment]
No, Moira will support both graphite and prometheus.
