### ISSUE TITLE
InvalidProgramState then schedule is null on Front then edit trigger

### ISSUE THREAD

**Issue by borovskyav** [moira-alert/moira#401]
Пофиксить ситуацию когда с сервера прилетает расписание равное null. Кажется это нормальное поведение. Стоит просто делать стандартное расписание.

**Comment by hv7214** [comment]
@borovskyav can you elaborate this ?

**Comment by EduardZaydler** [comment]
fixed in https://github.com/moira-alert/moira/pull/1116 https://github.com/moira-alert/web2.0/pull/543
