### ISSUE TITLE
Triggers do not record a value if sending graphite "-1" magic value for timestamp

### ISSUE THREAD

**Issue by imavroukakis** [moira-alert/moira#426]
- Steps to replicate
	- Create a new trigger
	- send data using `-1` as datestamp e.g. `echo "DevOps.my_server.hdd.freespace_mbytes 9 -1" | nc localhost 2003`
	- Trigger records data sent, but no value is present
	![image](https://user-images.githubusercontent.com/1764981/65226195-5834af80-dabe-11e9-8045-277db9259b1f.png)

Any subsequent data sent, is ignored and you have to delete the trigger and recreate it.

**Comment by borovskyav** [comment]
Related to this path of graphite documentation https://graphite.readthedocs.io/en/latest/feeding-carbon.html#step-3-understanding-the-graphite-message-format
