### ISSUE TITLE
Improve Advanced Mode

### ISSUE THREAD

**Issue by beevee** [moira-alert/moira#428]
Сейчас Advanced Mode работает крайне ущербно:

1. В t1 можно указать паттерн, который разложится на несколько метрик. В остальных таргетах можно указывать только паттерны, которые разложатся строго в одну метрику.
2. Если срабатывает эвент, в уведомлении пишется имя и значение метрики из t1, даже если сработало из-за превышения какой-то другой метрики в t2 или t3.

Пользователи это не понимают, делают наугад и приходят с вопросами, когда у них все работает неожиданным образом.

Предлагаю доработать Advanced Mode cледующим образом:

1. Каждый из таргетов может раскрываться либо строго в одну, либо в N метрик, где N одинаковое для всех таргетов.
2. Если несколько таргетов раскрываются в N метрик, то их имена должны совпадать. Если таргет раскрывается в одну метрику, то считаем, что он раскрывается в N метрик с нужными именами, у которых одинаковые значения.
3. Во всех остальных случаях триггер должен находиться в состоянии ошибки и объяснять пользователю через веб-интерфейс, что так нельзя (в том же духе, как сообщается о нескольких метриках с одинаковыми именами).
4. Триггер, таким образом, считается состоящим из N метрик, по каждой из которых отдельно вычисляется выражение и отслеживается состояние.
5. При срабатывании триггера в уведомлении приходит: имя метрики (которое совпадает во всех таргетах), значение всех соответствующих метрик из t1, t2 и т.д., и текст выражения.
6. В веб-интерфейсе в истории событий отображается тоже не только t1, но и значение всех остальных метрик из следующих таргетов.
7. Чтобы избежать неявного поведения, в форме редактирования триггера для Advanced Mode нужно добавить к каждому таргету переключатель: может ли этот таргет раскрываться в несколько метрик или нет. Пользователь должен явным образом указать, как по его задумке раскрывается каждый таргет. По умолчанию, для сохранения обратной совместимости, считаем переключатель включенным для t1 и выключенным для остальных таргетов.
8. Документацию надо переписать.

**Comment by beevee** [comment]
Пример 1.

У меня есть метрики:
`host1.loadavg` — Load Average на сервере host1
`host2.loadavg`
`host3.loadavg`
`host1.cpu_count` — количество ядер на сервере host1
`host2.cpu_count`
`host3.cpu_count`

Я создаю Advanced Mode триггер:
t1 — `aliasByNode(*.loadavg, 0)`
t2 — `aliasByNode(*.cpu_count, 0)`
expression — `t1/t2 > 1 ? ERROR : OK`

В результате в триггере образуется три метрики, по которым отдельно отслеживается состояние:
`host1`
`host2`
`host3`

Если срабатывает эвент, в уведомлении я получаю, к примеру:
`host1: t1 = 100, t2 = 10, t1/t2 > 1 ? ERROR : OK` (внешний вид уведомления можно обсудить отдельно)

**Comment by beevee** [comment]
Пример 2.

У меня есть метрики:
`host1.loadavg` — Load Average на сервере host1
`host2.loadavg`
`host3.loadavg`
`all_hosts.cpu_count` — количество ядер на любом из серверов (везде одинаковое)

Я создаю Advanced Mode триггер:
t1 — `aliasByNode(*.loadavg, 0)`
t2 — `all_hosts.cpu_count`
expression — `t1/t2 > 1 ? ERROR : OK`

В результате в триггере образуется три метрики, по которым отдельно отслеживается состояние:
`host1` — выражение вычисляется для `t1 = host1.loadavg, t2 = all_hosts.cpu_count`
`host2` — выражение вычисляется для `t1 = host2.loadavg, t2 = all_hosts.cpu_count`
`host3`

Если срабатывает эвент, в уведомлении я получаю, к примеру:
`host1: t1 = 100, t2 = 10, t1/t2 > 1 ? ERROR : OK` (внешний вид уведомления можно обсудить отдельно)

**Comment by beevee** [comment]
Поскольку среди таргетов могут быть такие, которые раскрываются в одну метрику (т.е. имя будет только одно), имена для результирующих метрик нужно брать из первого таргета, который раскрывается больше чем в одну метрику. Если все таргеты раскрываются в одну метрику — ну что ж, значит она одна и есть.

**Comment by beevee** [comment]
Можно обсудить вариант, при котором не обязано быть одинаковое количество метрик во всех таргетах. Недостающие значения заменять на какое-то дефолтное (ноль? задавать через настройки триггера?). Но я считаю, что это только к выстрелам в ногу будет приводить.

**Comment by borovskyav** [comment]
Да, кажется этот краевой сценарий нужно обрубать на корню, нет сопоставленной метрики в одном из таргетов - ничего не делаем.

**Comment by litleleprikon** [comment]
Was closed accidentally. Will close it when frontend will be merged and documentation will be updated.
