### ISSUE TITLE
Aggregate notifications for mass problems

### ISSUE THREAD

**Issue by SilentCatVallis** [moira-alert/moira#44]
Sometimes something bad happens. And many of your triggers fall into NODATA (for example).
It would be nice if Moira could notice the massive problems and replace one million messages with one. One message with the text "everywhere everything is bad" is much more informative than a flurry of alerts.

**Comment by sashasushko** [comment]
Частично этот кейс решит moira-alert/moira/issues/209

**Comment by beevee** [comment]
Will solve in #8
