### ISSUE TITLE
[Moira-web] Import/Export buttons for triggers, notifications and subscriptions

### ISSUE THREAD

**Issue by beliys** [moira-alert/moira#448]
Hi! It would be nice to have the additional ability to do Import/Export triggers, notifications and subscriptions via the web interface. I think it would be convenient to have such an opportunity and I suspect that it is not very difficult to implement because API calls are ready.

**Comment by idoqo** [comment]
Hi @litleleprikon, I'd love to work on this with some more info.

Does this mean exporting the JSON response that is, letting a user download it as a JSON file?

**Comment by beliys** [comment]
@idoqo, unfortunately @litleleprikon did not respond for a long time, but the original purpose of the task was to make this process simpler and more convenient for the end user. But we need to not only download JSON but also import previously exported settings from it.

**Comment by litleleprikon** [comment]
Hi @idoqo sorry that I missed your question. I believe that @beliys gave you an answer for your question.

**Comment by idoqo** [comment]
> Hi @idoqo sorry that I missed your question. I believe that @beliys gave you an answer for your question.

Yes, it did! I'll take a shot at it then. Thanks @beliys
