### ISSUE TITLE
error timezone in email

### ISSUE THREAD

**Issue by ihard** [moira-alert/moira#45]
in config notifier.yml
timezone: Europe/Moscow
in web interface - all ok
in email notifification - time UTC

**Comment by borovskyav** [comment]
Hi! Have you this problem in notification in another sender (for example, telegram)?
Or can you see log message during launch moira-notifier? You must see message like ```Timezone 'Europe/Moscow' load failed: 'error message'. Use UTC.``` or ```Timezone '%s' loaded.```

**Comment by ihard** [comment]
Yes, in telegram also UTC
in log
 Nov 12 23:56:51 moira systemd[1]: Started Moira is alerting system based on graphite data.
Nov 12 23:56:51 moira moira-notifier[4386]: 2017-11-12 23:56:51.266#011notifier#011INFO#011Timezone 'UTC' loaded.
Nov 12 23:56:51 moira moira-notifier[4386]: 2017-11-12 23:56:51.269#011notifier#011INFO#011Sender mail registered
Nov 12 23:56:51 moira moira-notifier[4386]: 2017-11-12 23:56:51.602#011notifier#011INFO#011Sender telegram registered
Nov 12 23:56:51 moira moira-notifier[4386]: 2017-11-12 23:56:51.602#011notifier#011DEBUG#011Moira Self State Monitoring disabled
Nov 12 23:56:51 moira moira-notifier[4386]: 2017-11-12 23:56:51.603#011notifier#011INFO#011Moira Notifier Fetching scheduled notifications started
Nov 12 23:56:51 moira moira-notifier[4386]: 2017-11-12 23:56:51.603#011notifier#011INFO#011Moira Notifier Fetching events started
Nov 12 23:56:51 moira moira-notifier[4386]: 2017-11-12 23:56:51.603#011notifier#011INFO#011Moira Notifier Started. Version: 2.0-beta1.2
Nov 12 23:56:51 moira moira-notifier[4386]: 2017-11-12 23:56:51.603#011notifier#011INFO#011Registered new telegram bot, checking for new messages

**Comment by borovskyav** [comment]
Oh, i have found some bugs in default configs in pkg. Fixed it here: https://github.com/moira-alert/moira/commit/2257ce5c917647b6dab63c30f532117f71978f63. Try to fix it in your configs

**Comment by ihard** [comment]
now is ok - thank you!
