### ISSUE TITLE
Show schedule timezone on trigger page

### ISSUE THREAD

**Issue by sashasushko** [moira-alert/moira#472]
> In trigger page the timezone is not shown. That can cause the bad observability of troubles with incorrect notifications schedule. I propose to add timezone to trigger edit page.

From https://github.com/moira-alert/web2.0/issues/279

**Comment by prateek2211** [comment]
By schedule timezone do you mean the timezone of user using the platform?
Would adding timezone beside `Add trigger` heading work fine?

**Comment by sashasushko** [comment]
@litleleprikon look at this, pls

**Comment by borovskyav** [comment]
In the first solution, we wanna show saved trigger timezone, because some of our users do not understand in which timezone the trigger is saved and why the schedule does not work correctly

**Comment by litleleprikon** [comment]
Hi @prateek2211 schedule timezone is a timezone saved in schedule part of trigger. It is called `tzOffset`. The timezone is hidden right now on trigger page. 

I propose to add timezone to this field on trigger page
![Screenshot 2020-01-29 at 10 32 39](https://user-images.githubusercontent.com/5058463/73336372-b6e71280-4282-11ea-8391-0bdb365f85da.png)

**Comment by prateek2211** [comment]
Thanks for the clarification

**Comment by sashasushko** [comment]
@prateek2211 thank you very much for help!

**Comment by beevee** [comment]
Wrong sign, guys :-(

If `tzOffset` is -300, it's GMT+5, not GMT-5.

@prateek2211 @sashasushko

**Comment by prateek2211** [comment]
oops!, allow me some time to correct it

**Comment by sashasushko** [comment]
@prateek2211 I think we need some unit test for convert function, that you wrote. What do you think?
