### ISSUE TITLE
StatusIndicator doesn't support 4-status circles

### ISSUE THREAD

**Issue by beevee** [moira-alert/moira#481]
See moira-alert/web2.0#281 for context.

![image](https://user-images.githubusercontent.com/1009675/72074018-f15c3000-3312-11ea-8f67-1d72b0adea28.png)

The reason why there is no circle after the arrow is that `StatusIndicator` component supports no more than 3 statuses: https://github.com/moira-alert/web2.0/blob/3f9ef887c8bdb76ee5b7829369e1a8d5e623edee/src/Components/StatusIndicator/StatusIndicator.jsx#L14

This issue can be reproduced only rarely on Notifications hidden page, when there is a lot of events in a single notification package. Still, worth fixing.

**Comment by NullByte08** [comment]
Can I work on this issue?

**Comment by litleleprikon** [comment]
Hi @NullByte08 feel free to contribute to Moira!

**Comment by sashasushko** [comment]
@NullByte08 how it doing? need some help?

**Comment by NullByte08** [comment]
I was facing a lot of errors while installing Moira on windows(on docker), so currently I am not working on this issue.

**Comment by sashasushko** [comment]
Okay.

**Comment by sashasushko** [comment]
p.s. For web developing it's no need to installing Moira on PC. Look at https://github.com/moira-alert/web2.0/blob/master/README.md

**Comment by hv7214** [comment]
@sashasushko I guess everywhere status is received as value and not array. In fact in `db.json` we are sending status as a value.

**Comment by litleleprikon** [comment]
@hv7214 can you please specify what exactly you want to ask?

**Comment by hv7214** [comment]
@litleleprikon ignore it :sweat_smile: I misunderstood something.

**Comment by hv7214** [comment]
i am picking this up.

**Comment by sashasushko** [comment]
@beevee there is changes from @hv7214, but his solution support only 4 colors. How you think, it's enough?

**Comment by hv7214** [comment]
Don't we have only 4-states right now ? But if you are planning to add more states in future then will surely make changes accordingly.

**Comment by hv7214** [comment]
For now we have switch cases defined to handle different number of status. It's kinda a static approach. I was thinking about dynamic approach. LIke render colours depending on the size of `statuses` array. If you think it's good idea then i'll be happy to think over it : )

**Comment by beevee** [comment]
@sashasushko @hv7214 let's not overengineer this right now. Looks good to merge.
