### ISSUE TITLE
Send hello message in telegram chats on every start message in group chats

### ISSUE THREAD

**Issue by litleleprikon** [moira-alert/moira#488]
# BUG REPORT

## What did you expect to see?
When I send message `/start@MoiraBot` in telegram group chats and this command was sent before bot do not reply for this message.

## What did you see instead?
Bot should reply for my message.

**Comment by beevee** [comment]
It does reply. But only in personal chats, not in group chats. Weird logic.

**Comment by litleleprikon** [comment]
@beevee My fault. The issue is about group chats. I will edit description.

BTW Does anyone know the reason of this behaviour? Is it really a bug? As we can see this behaviour was added manually but no-one knows the reason.

**Comment by adrijshikhar** [comment]
@beevee i would like to work on this issue, i have already setup the repo.
Can you please assign it to me?

**Comment by litleleprikon** [comment]
@adrijshikhar  You can work on it

**Comment by shashikant231** [comment]
hello everyone .can anyone help to find the repo for this issue.i am  willing to work on this issue.
Thanks!!

**Comment by alishamohanty** [comment]
That's a great feature to be incorporated, it will help the user to have a belonging feel. In addition to greeting, we should say something more. Like adding "please have a look at the pinned message" etc.  If I am getting it right we want to make it using Telegram bot right @litleleprikon ?

**Comment by alishamohanty** [comment]
I have prior experience with working with Bots, please let me know if I can work on it @litleleprikon .Thank you.

**Comment by alishamohanty** [comment]
@sashasushko Your ideas about it?

**Comment by uwaiszaki** [comment]
@beevee Can I work on this issue?

**Comment by litleleprikon** [comment]
Hi @uwaiszaki yes, you can work on it
