### ISSUE TITLE
Fulltext search breaks on ALL CAPS

### ISSUE THREAD

**Issue by beevee** [moira-alert/moira#512]
# BUG REPORT

## What version of Moira are you using (`[binary] --version`)?

<details><pre>

$ api --version
Moira Api
Version: 2020-03-04.4095911
Git Commit: 40959110ada8c17ab6d6f594c61bcafba5cf6b3f
Go Version: go1.13.1

</pre></details>

## What did you expect to see?

I expected fulltext search to work regardless of query string case.

## What did you see instead?

Instead, it doesn't work when query string is ALL CAPS. See pictures.

![image](https://user-images.githubusercontent.com/1009675/76736499-ba7a1e80-6788-11ea-9326-0d5180c47036.png)

![image](https://user-images.githubusercontent.com/1009675/76736506-bfd76900-6788-11ea-9cef-a74373acc5ce.png)

![image](https://user-images.githubusercontent.com/1009675/76736511-c36af000-6788-11ea-8181-d8c3ea59b8e1.png)

**Comment by alishamohanty** [comment]
Even if we make any letter other than the first letter capital, it is unable to search it. For example meDI or meDi also doesn't work, even if the exact word is present.

**Comment by alishamohanty** [comment]
I am new to Go, so it might take a few days to complete the issue, but I would like to work on it.

**Comment by vikasprashar99** [comment]
yes can you please elaborate the issue

**Comment by beevee** [comment]
@vikasprashar99 elaborate how? What part of this issue you don't understand?

**Comment by vikasprashar99** [comment]
@beevee so when you write in caps it isn't able to search?

**Comment by beevee** [comment]
@vikasprashar99 please, look at the screenshots I included in the task description. Or download Moira and try to reproduce this yourself.

**Comment by vikasprashar99** [comment]
okay i will check, have already downloaded

**Comment by hv7214** [comment]
@beevee i think this issue should be merged with this one https://github.com/moira-alert/moira/issues/345

**Comment by beevee** [comment]
#345 is too vague. This issue, on the other hand, is very concrete and easy to validate.

**Comment by hv7214** [comment]
@beevee I meant there are many problems regarding `Search bar`. So it will be better to merge them all : )

**Comment by beevee** [comment]
This specific problem has a very simple solution: convert search string to lowercase on frontend. Everything works, issue solved, one user made happy.

#345 is more like "we are generally unhappy with the search algorithm, but we can not specifically tell you why, and we don't know exactly how we want it to behave". Impossible to implement and check. I promise you, if we merge this with #345, it will never be finished, and zero users will become happy as a result.

**Comment by hv7214** [comment]
@beevee i understood your point, you are right : ) 
:+1:
