### ISSUE TITLE
moira-cli-2.0.0-1.x86_64.rpm doesn't work

### ISSUE THREAD

**Issue by 2autunni** [moira-alert/moira#55]
Trying to install moira-cli using 
`rpm -i moira-cli-2.0.0-1.x86_64.rpm`
the command fails with the message 

> file/usr/lib/systemd/system from install of  moira-cli-2.0.0-1.x86_64 conflicts with file from package systemd-219-42.el7_4.4.x86_64

this happens because the package contains the empty directory /usr/lib/systemd/system/

```
[root@moira02 moira_pkg]# rpm -qlp moira-cli-2.0.0-1.x86_64.rpm
/etc/moira/cli.yml
/usr/bin/moira-cli
/usr/lib/systemd/system

```

**Comment by melnikk** [comment]
RPM will fixed with next feature tag.
