### ISSUE TITLE
malformed config files installed by rpm

### ISSUE THREAD

**Issue by 2autunni** [moira-alert/moira#56]
The RPMs of  moira-filter, moira-checker and moira-notifier install malformed config files; in each there is at row 6:

```
graphite:
  enabled: ""
```

instead of 

```
graphite:
  enabled: true
```

so starting services fails with errors like these:

> 
> gen 09 09:21:19  moira-filter[2044]: Can not read settings: Can't parse config file [/etc/moira/filter.yml] [yaml: unmarshal errors:
> gen 09 09:21:19  moira-filter[2044]: line 6: cannot unmarshal !!str `` into bool]
> 

/etc/moira/notifier.yml has one more problem:

```
  moira_selfstate:
    enabled: "false"
```

instead of 

```
  moira_selfstate:
    enabled: false
```
so strarting the service returns this error

> gen  09 10:34:57  moira-notifier[4574]: line 18: cannot unmarshal !!str `false` into bool]

**Comment by melnikk** [comment]
RPM will fixed with next feature tag.
