### ISSUE TITLE
Different behaviour of different Carbon API versions

### ISSUE THREAD

**Issue by litleleprikon** [moira-alert/moira#592]
# BUG REPORT

In this issue I want to collect all differences in behaviour of different versions of Carbon API.

**Comment by litleleprikon** [comment]
Function `movingAverage` in CarbonAPI version `v0.0.0-20201019162650-b789c0eaed8a` works like `consolidateBy(min)`

**Comment by androndo** [comment]
Function groupByNode not support `'average'`, but allow `'avg'` instead.

**Comment by kissken** [comment]
We are currently using the current version of the library. We track and fix different behaviour, when it is possible
