### ISSUE TITLE
Not working "mute new metrics" checkbox

### ISSUE THREAD

**Issue by litleleprikon** [moira-alert/moira#597]
# BUG REPORT

## What did you expect to see?
When creating new trigger if checkbox "mute new metrics" is set to true  then when trigger first time stay OK notification should not be sent.

## What did you see instead?
Notifications sent.

**Comment by burnerlee** [comment]
@litleleprikon, may I take up this issue and start working on this?

**Comment by litleleprikon** [comment]
Hi @burnerlee  of course you can

**Comment by burnerlee** [comment]
thank you so much

**Comment by kissken** [comment]
now it's ok. I'll close issue :)
