### ISSUE TITLE
Timestamp format in alert email

### ISSUE THREAD

**Issue by 0x62ash** [moira-alert/moira#60]
Just got alert email with timestamp - `09:51 17.01.2018`.
Is it possible to change it to ISO8601 with time zone?

**Comment by borovskyav** [comment]
Hm, we can add event timestamp format as notifier configurable parameter, is this decision for you?

**Comment by 0x62ash** [comment]
Yes, please

**Comment by titusjaka** [comment]
Closed by #74

**Comment by titusjaka** [comment]
Reopen until stable version is published on docker hub.
