### ISSUE TITLE
Error when first creating trigger using MetricElements in description (slice index out of range)

### ISSUE THREAD

**Issue by MironovOleg** [moira-alert/moira#639]
# BUG REPORT

**Moira API Version**: 2021-04-23.6e233d0 and earlier versions.

## What did you expect to see?
*Example trigger description:*
```
{{range $v := .Events }}
Application dashboards:
[{{index $v.MetricElements 1}}](https://grafana.example.com/d/VmYB54DZz/dashboard?orgId=1&var-Env=production&var-Project=example&var-Application={{index $v.MetricElements 1}})
{{end}}
```
When I create a trigger with this description, I expect it to be created without error. And with the advent of events - the description will be filled with event elements (MetricElements).

## What did you see instead?
Moira API returns me the following error - `Error rendering response: you have an error in your Go template: template: populate-description:1:255: executing "populate-description" at <index $v.MetricElements 1>: error calling index: reflect: slice index out of range`. This happens because the trigger is new and there were no events in it yet.

**Comment by MironovOleg** [comment]
[Documentation](https://moira.readthedocs.io/en/latest/user_guide/advanced.html#templates).

It turns out that this is solved by creating the conditions for events.
Example:
```
{{ range $i, $v := .Events }}
{{ if ne $i 0 }}
Application dashboards:
[{{index $v.MetricElements 1}}](https://grafana.example.com/d/VmYB54DZz/dashboard?orgId=1&var-Env=production&var-Project=example&var-Application={{index $v.MetricElements 1}})
{{end}}
{{end}}
```

**Comment by zhelyabuzhsky** [comment]
> It turns out that this is solved by creating the conditions for events.

@MironovOleg Thanks for your detailed example. It will be helpful to others.
