### ISSUE TITLE
Add images to notify

### ISSUE THREAD

**Issue by kolobaev** [moira-alert/moira#7]
Всем привет!
Во всех API интерфейсах графита, есть возможность рендерить картинку относительно метрики.
Очень хочется, иметь возможность, в нотификаторе, включить рассылку картинок для Slack и почты, как это сделано к примеру в Графане.
Картинку можно генерить онлайни и заливать её на расшаренный WEBDAV сервер (для начала). После чего постить ссылку на неё в слак и почту.

**Comment by kamaev** [comment]
implemented in: https://github.com/moira-alert/moira/pull/148
will be featured in upcoming 2.4 release
