### ISSUE TITLE
prometheus and moira

### ISSUE THREAD

**Issue by logicall** [moira-alert/moira#71]
Добрый день!

Скажите, а вы не рассматривали использование prometheus (https://prometheus.io) как дополнительный источник метрик?

**Comment by borovskyav** [comment]
Привет! Сейчас мы не рассматриваем прометеус по нескольким причинам: у прометеуса как я слышал своя вполне неплохая система алертинга, делать еще одну смысла не видим; сейчас мы сосредоточены на более плотной интеграции мойры и графита и развитии нотификаций. Если у тебя есть годные аргументы, почему нам стоит использовать мойру для прометеуса, пиши, нам интересно)
