### ISSUE TITLE
Enable alerts only for selected days interval

### ISSUE THREAD

**Issue by 0x62ash** [moira-alert/moira#78]
Hello,
We need alerts only for interval 1-25 jan, 1-25 apr, 1-25 jul, 1-25 oct (да, да, это отчетсность по НДС).
This is because our metrics could show 0 value on days outside these intervals.

**Comment by titusjaka** [comment]
Hello,
We discussed this issue and came to the conclusion it doesn't fit Moira scheme. If you want to automate this behavior, you can do it using CI/CD (e.g. Teamcity) and [Moira Trigger Role](https://galaxy.ansible.com/moira-alert/moira-trigger-role).
