### ISSUE TITLE
Add support of multiple senders with type: mail

### ISSUE THREAD

**Issue by horpak** [moira-alert/moira#821]
# FEATURE
Notifier supports only one sender with type mail, but sometimes there is such situation when you need to send alerting emails from different addresses/to different smtp connections/with different templates/etc
## Summary

Main idea is to give the ability to set up multiple email senders, each one with its own settings.It seems to me that it would be convenient to do it by the same mechanism like it done with webhooks -  with differentiation by field ```name```.

### Details

<details>
I've made some experiments with adding multiple email senders. It looks like that connection that goes lower in notifier.yml just overrides upper connection settings.
</details>

**Comment by kissken** [comment]
**mini-note for dev:** don't forget fix documentation

**Comment by kissken** [comment]
**add ability in others senders too**

**Comment by almostinf** [comment]
Hi, I have made support for multiple senders in #994, and therefore I will close the issue
