### ISSUE TITLE
API for exporting and importing triggers, delivery channels and subscriptions

### ISSUE THREAD

**Issue by usbulat** [moira-alert/moira#84]
Hello,

Is there any http api for exporting triggers, delivery channels and subscriptions (e.g. to json) to backup them, and any api for their import to new moira installation?

**Comment by titusjaka** [comment]
Hi Bulat,

If you are familiar with Python, you can use Moira Python Client for these goals: https://github.com/moira-alert/python-moira-client.

**Comment by titusjaka** [comment]
Hi @usbulat,

Let me know, if you have further questions about API? If Python Client doesn't fit your purposes, you can use HTTP directly. Unfortunately, API is not listed in documentation yet, but you can dive into it here: https://github.com/moira-alert/moira/blob/master/api/handler/handler.go

If you have any question, feel free to ask here or in [Telegram Chat](https://t.me/moira_alert). (You even speak Russian in that chat :) )

**Comment by usbulat** [comment]
Hi @titusjaka ,

Your link to handler.go file really helped me. Thank you so much!
