### ISSUE TITLE
алерты в Telegram падают вне зависимости от настроек в "watch time"

### ISSUE THREAD

**Issue by vraskoshnyy** [moira-alert/moira#89]
Заметили странное поведение - алерты от Мойра приходят во интервал времени, который не входит в "watch time".
Т.е. например, в watch time указано "At specific interval: 12:00 - 23:59"
а уведомление в телегу прилетело в 10:09.
Проверьте, пожалуйста. 
Спасибо.

**Comment by borovskyav** [comment]
Привет! Мы постараемся на днях посмотреть, воспроизвести у себя, спасибо =)

**Comment by vraskoshnyy** [comment]
Привет. Получилось?
У меня стабильно воспроизводится(

**Comment by vraskoshnyy** [comment]
И ещё хотел добавить. Триггер может быть со статусом error в watch time, которое нам не интересно (за его границами), но при этом на общем dashboard он будет показан с переключателем "Only problems". Кажется, что это не совсем логично. Т.е. если мне не нужно знать состояние триггера в период, например, с 00 до 07, то зачем его показывать как с "проблему"? Может сделать системную настройку, чтобы можно было скрывать такие триггеры по времени и на общем dashboard?

**Comment by borovskyav** [comment]
Привет! Так увлеклись релизом 2.3 что совсем забыли. На следующей неделе зарелизим 2.3 и постараемся заняться проверкой бага одной из первых задач. Сории за ожидание(

**Comment by borovskyav** [comment]
По поводу watch time - спасибо за реквест, мы сейчас активно пречесываем логику с мейнтенансом метрик в триггере, в релизе 2.3 немного переработали механику работы мейнтенанса. В 2.4 продолжим причесывать, накопилось уже несколько разных реквестов, например https://github.com/moira-alert/web2.0/issues/153. Добавили твой реквест в список.

**Comment by vraskoshnyy** [comment]
Привет, я живу в MSK.
"tzOffset":-300"

**Comment by vraskoshnyy** [comment]
Круто, спасибо)

**Comment by borovskyav** [comment]
https://github.com/moira-alert/web2.0/issues/172

**Comment by vraskoshnyy** [comment]
Понял, спасибо.

**Comment by sashasushko** [comment]
Fixed on front.

**Comment by titusjaka** [comment]
moira-alert/web2.0#173

**Comment by sashasushko** [comment]
> нужно будет пересохранить триггер

This may not help. I check today trigger edit logic.

Because, I think, we don't change timezone, when user edit trigger. It's unobvious behavior. So... we need to discuss it before change this logic.

**Comment by sashasushko** [comment]
Unfortunately, it's true. Timezone set once when trigger create.

@vraskoshnyy you need to recreate trigger.

We will think how fix this behavior in next release.

**Comment by vraskoshnyy** [comment]
@sashasushko  ок, пересоздам
